/**
 * Docker bootstrap orchestrator (slice 7 of CRM arc).
 *
 * Writes the compose file under ~/.founder-os/crm/<slug>/, brings the
 * stack up scoped to project `founder-os-crm-<slug>`, waits for the
 * Frappe web container to respond on /api/method/ping, then runs the
 * one-shot first-boot script to create the site + install the CRM app
 * + generate the API key pair.
 *
 * Implementation deliberately keeps file IO + spawn injectable so the
 * unit tests can mock them. The first-boot script + compose file live
 * under packages/crm-providers/assets/ but the orchestrator reads them
 * at runtime via the caller-provided fs (the desktop sidecar passes a
 * Node fs adapter).
 *
 * Idempotent. If the compose project is already running, the
 * orchestrator skips up + first-boot and just verifies the ping.
 */
import { CRM_DOCKER_DEFAULT_PORT, CRM_DOCKER_DEFAULT_SOCKETIO_PORT } from "@founder-os/crm-core";

import { createFrappeClient, type FrappeClient } from "./frappe-client.js";
import {
  DockerNotFoundError,
  spawnDocker,
  type DockerSpawnOpts,
  type DockerSpawnResult,
} from "./spawn.js";

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export class DockerBootstrapTimeoutError extends Error {
  override readonly name = "DockerBootstrapTimeoutError";
  constructor(readonly waitedMs: number) {
    super(
      `Frappe web container did not respond on /api/method/ping within ${waitedMs}ms. ` +
        `Check 'docker compose -p founder-os-crm-<slug> logs frontend' for details.`,
    );
  }
}

export class DockerBootstrapInstallError extends Error {
  override readonly name = "DockerBootstrapInstallError";
  constructor(readonly stdout: string, readonly stderr: string) {
    super(`first-boot install failed. See stderr for details.`);
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type FileWriter = {
  /**
   * Write text to an absolute path. Creates parent directories as needed.
   */
  writeFile(path: string, content: string): Promise<void>;
  /**
   * Read text from an absolute path. Throws if the file is missing.
   */
  readFile(path: string): Promise<string>;
  /**
   * Whether a file or directory exists at the given path.
   */
  exists(path: string): Promise<boolean>;
};

export type DockerBootstrapOpts = {
  ventureSlug: string;
  /**
   * Resolved data directory (no `~` tokens). Compose mounts
   * `${dataDir}/sites` and `${dataDir}/db`.
   */
  dataDir: string;
  /**
   * Host port the frontend binds. Defaults to CRM_DOCKER_DEFAULT_PORT.
   */
  port?: number;
  /**
   * Host port the socketio binds. Defaults to CRM_DOCKER_DEFAULT_SOCKETIO_PORT.
   */
  socketioPort?: number;
  adminEmail: string;
  /**
   * The compose file under packages/crm-providers/assets/. Caller
   * passes the absolute path resolved by their packaging layer.
   */
  composeAssetPath: string;
  /**
   * Path to first-boot.sh under packages/crm-providers/assets/.
   */
  firstBootAssetPath: string;
  /**
   * Where to write the venture-specific compose file. Defaults to
   * `${dataDir}/docker-compose.yml`.
   */
  composeOutputPath?: string;
  /**
   * Maximum wait for the Frappe web container's /api/method/ping to
   * return 200. Defaults to 90s.
   */
  pingTimeoutMs?: number;
  /**
   * File IO adapter. The desktop sidecar passes a Node fs adapter.
   */
  fs: FileWriter;
  /**
   * Injected docker spawner (tests use this).
   */
  spawnDockerImpl?: (opts: DockerSpawnOpts) => Promise<DockerSpawnResult>;
  /**
   * Injected fetch (passed to the ping FrappeClient).
   */
  fetchImpl?: typeof fetch;
};

export type DockerBootstrapResult = {
  composeProject: string;
  siteUrl: string;
  /**
   * The Administrator API key+secret generated by first-boot.sh.
   * Caller stores this encrypted, never plaintext on disk.
   */
  apiKey: string;
  apiSecret: string;
  /**
   * "fresh" when the compose project was just created on this run,
   * "reused" when it was already up.
   */
  state: "fresh" | "reused";
};

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------

export async function bootstrapDockerStack(
  opts: DockerBootstrapOpts,
): Promise<DockerBootstrapResult> {
  const port = opts.port ?? CRM_DOCKER_DEFAULT_PORT;
  const socketioPort = opts.socketioPort ?? CRM_DOCKER_DEFAULT_SOCKETIO_PORT;
  const composeProject = `founder-os-crm-${opts.ventureSlug}`;
  const composeOutputPath =
    opts.composeOutputPath ?? `${opts.dataDir}/docker-compose.yml`;
  const dockerSpawn = opts.spawnDockerImpl ?? spawnDocker;
  const pingTimeoutMs = opts.pingTimeoutMs ?? 90_000;

  // 0. Pre-flight: Docker daemon reachable?
  try {
    const v = await dockerSpawn({
      args: ["version", "--format", "{{.Server.Version}}"],
      timeoutMs: 2000,
    });
    if (v.exitCode !== 0) throw new DockerNotFoundError();
  } catch (cause) {
    if (cause instanceof DockerNotFoundError) throw cause;
    throw new DockerNotFoundError();
  }

  // 1. Already running?
  const running = await composeIsRunning(dockerSpawn, composeProject);
  let state: "fresh" | "reused" = "fresh";

  if (!running) {
    // 2. Write compose file from asset template.
    if (!(await opts.fs.exists(opts.composeAssetPath))) {
      throw new Error(
        `Compose asset not found at ${opts.composeAssetPath}. ` +
          `Did packaging copy packages/crm-providers/assets/docker-compose.yml?`,
      );
    }
    const composeBody = await opts.fs.readFile(opts.composeAssetPath);
    await opts.fs.writeFile(composeOutputPath, composeBody);

    // 3. docker compose up -d.
    const envInjected = [
      `FOUNDER_OS_CRM_PORT=${port}`,
      `FOUNDER_OS_CRM_SOCKETIO_PORT=${socketioPort}`,
      `FOUNDER_OS_CRM_DATA_DIR=${opts.dataDir}`,
    ];
    const upRes = await dockerSpawn({
      args: [
        "compose",
        "-p",
        composeProject,
        "-f",
        composeOutputPath,
        ...envInjected.flatMap((e) => ["--env", e]),
        "up",
        "-d",
      ],
      timeoutMs: 45_000,
    });
    if (upRes.exitCode !== 0) {
      throw new DockerBootstrapInstallError(upRes.stdout, upRes.stderr);
    }
  } else {
    state = "reused";
  }

  const siteUrl = `http://localhost:${port}`;

  // 4. Wait for ping.
  await waitForPing(siteUrl, pingTimeoutMs, opts.fetchImpl);

  // 5. If fresh, run first-boot.sh inside the configurator container.
  let apiKey: string;
  let apiSecret: string;
  if (state === "fresh") {
    if (!(await opts.fs.exists(opts.firstBootAssetPath))) {
      throw new Error(
        `first-boot asset not found at ${opts.firstBootAssetPath}.`,
      );
    }
    const firstBootBody = await opts.fs.readFile(opts.firstBootAssetPath);
    const firstBootDestination = `${opts.dataDir}/first-boot.sh`;
    await opts.fs.writeFile(firstBootDestination, firstBootBody);

    const adminPassword = generateAdminPassword();
    const execRes = await dockerSpawn({
      args: [
        "compose",
        "-p",
        composeProject,
        "exec",
        "-T",
        "-e",
        `SITE_NAME=crm.localhost`,
        "-e",
        `ADMIN_EMAIL=${opts.adminEmail}`,
        "-e",
        `ADMIN_PASSWORD=${adminPassword}`,
        "backend",
        "bash",
        firstBootDestination,
      ],
      timeoutMs: 180_000,
    });
    if (execRes.exitCode !== 0) {
      throw new DockerBootstrapInstallError(execRes.stdout, execRes.stderr);
    }
    const parsed = parseFirstBootOutput(execRes.stdout);
    apiKey = parsed.key;
    apiSecret = parsed.secret;
  } else {
    // For reused projects, callers should have the key cached. If they
    // don't, they need to call /api/method/.../generate_keys themselves
    // via the client. This branch returns empty strings so the caller
    // surfaces the gap explicitly.
    apiKey = "";
    apiSecret = "";
  }

  return {
    composeProject,
    siteUrl,
    apiKey,
    apiSecret,
    state,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function composeIsRunning(
  dockerSpawn: (opts: DockerSpawnOpts) => Promise<DockerSpawnResult>,
  project: string,
): Promise<boolean> {
  try {
    const res = await dockerSpawn({
      args: [
        "compose",
        "-p",
        project,
        "ps",
        "--status",
        "running",
        "--format",
        "json",
      ],
      timeoutMs: 5000,
    });
    if (res.exitCode !== 0) return false;
    return res.stdout.trim().length > 0;
  } catch {
    return false;
  }
}

async function waitForPing(
  siteUrl: string,
  timeoutMs: number,
  fetchImpl?: typeof fetch,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  const POLL_MS = 2000;

  // Build a client. We don't have an API key yet on first boot, so the
  // request will fail auth -- but it'll fail with 401, not a connect
  // refusal. That's good enough to know the container is responding.
  let client: FrappeClient;
  try {
    client = createFrappeClient({
      siteUrl,
      apiKey: "ping-stub",
      apiSecret: "ping-stub",
      ...(fetchImpl !== undefined ? { fetchImpl } : {}),
    });
  } catch {
    throw new DockerBootstrapTimeoutError(0);
  }

  while (Date.now() < deadline) {
    try {
      await client.request({ method: "GET", path: "/api/method/ping" });
      return;
    } catch (err) {
      // 401 = container responding, just unauthenticated. Treat as ok.
      if (err instanceof Error && /401/.test(err.message)) return;
      await sleep(POLL_MS);
    }
  }
  throw new DockerBootstrapTimeoutError(timeoutMs);
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function generateAdminPassword(): string {
  // 16 chars, alphanumeric. Caller surfaces this to the user via the
  // gate UI so they can change it on first Frappe login.
  const chars = "abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let out = "";
  for (let i = 0; i < 16; i += 1) {
    out += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return out;
}

function parseFirstBootOutput(stdout: string): { key: string; secret: string } {
  let key = "";
  let secret = "";
  for (const line of stdout.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith("KEY=")) key = trimmed.slice(4);
    else if (trimmed.startsWith("SECRET=")) secret = trimmed.slice(7);
  }
  if (!key || !secret) {
    throw new DockerBootstrapInstallError(stdout, "Could not parse KEY/SECRET lines from first-boot output.");
  }
  return { key, secret };
}
