/**
 * createBackendExportStep -- slice 4 of backend arc.
 *
 * Asks the provider for the canonical BackendExport (provider-agnostic
 * JSON BUILD consumes) and writes it to
 * `12_backend/backend-export.json`. Also regenerates `12_backend/sdk/`
 * with three small TS files:
 *
 *  - client.ts -- thin client wrapper hardcoded to instance.baseUrl
 *  - types.ts  -- one TS interface per collection field list
 *  - hooks.ts  -- React Query / SWR hooks per collection (skeletal --
 *                 unconditional today, build.framework gating in the
 *                 BUILD-consumer slice)
 *
 * The SDK files are intentionally generated by THIS step (not BUILD)
 * because we want the file shapes typecheckable as soon as BACKEND
 * finishes -- BUILD just imports them. This mirrors how the dual-handoff
 * arc emits handoff-export.json at HANDOFF and lets BUILD consume.
 *
 * Idempotent: regenerated every run. Hand-edits inside 12_backend/sdk/
 * are NOT preserved (the user owns their downstream BUILD output, not
 * this generated layer).
 *
 * Deterministic. No LLM calls -- the export shape is fully derived from
 * provider state. If the provider's export() needs network access (e.g.
 * tier_0 PocketBase admin API), failures surface here verbatim.
 */
import {
  type BackendExport,
  type BackendInstance,
  type BackendProvider,
  type Collection,
  type Field,
  type FieldKind,
} from "@founder-os/backend-core";
import type { VentureManifest } from "@founder-os/domain";
import {
  getBackendDir,
  getBackendExportPath,
  getBackendSdkDir,
} from "@founder-os/workspace-core";

import type { Filesystem } from "../fs.js";
import {
  renderSupabaseClientTs,
  renderSupabaseHooksTs,
  renderSupabaseTablesTs,
  renderSupabaseTypesTs,
} from "./supabase-build-codegen.js";

export type CreateBackendExportContext = {
  fs: Filesystem;
  manifest: VentureManifest;
  ventureRoot: string;
  provider: BackendProvider;
  instance: BackendInstance;
  /**
   * Collections the schema step derived + applied. Forwarded to the
   * provider's export() implementation so providers that can't read
   * their own live schema (the stub tiers) still emit a faithful
   * BackendExport.
   */
  collections: Collection[];
  runId?: string;
};

export type CreateBackendExportResult = {
  status: "done";
  exportPath: string;
  /**
   * Paths to the per-engine SDK files. `tables` is only present when
   * the resolved engine is Supabase (slice 6 of the Supabase arc); for
   * PocketBase / stubs it's undefined.
   */
  sdkPaths: { client: string; types: string; hooks: string; tables?: string };
  collectionCount: number;
  /**
   * Whether the provider returned a non-empty collection list -- useful
   * for the runner's success log + the review-gate UI.
   */
  hasLiveCollections: boolean;
  notes: string[];
};

// ---------------------------------------------------------------------------
// SDK file rendering
// ---------------------------------------------------------------------------

function renderClientTs(exp: BackendExport): string {
  return [
    "// AUTO-GENERATED by @founder-os/pipeline-runner createBackendExportStep.",
    "// Re-run the BACKEND stage to regenerate. BUILD consumes this via",
    "// the @/lib/backend import alias.",
    "",
    `export const BACKEND_BASE_URL = ${JSON.stringify(exp.baseUrl)};`,
    `export const BACKEND_ENGINE = ${JSON.stringify(exp.engine)};`,
    "",
    "/**",
    " * Resolve the runtime base URL. Reads VITE_PB_URL when present so the",
    " * BUILD scaffold can override per-environment without regenerating.",
    " */",
    "export function resolveBackendBaseUrl(): string {",
    "  if (typeof import.meta !== \"undefined\") {",
    "    const env = (import.meta as { env?: Record<string, string> }).env;",
    "    const fromEnv = env?.VITE_PB_URL;",
    "    if (fromEnv) return fromEnv;",
    "  }",
    "  return BACKEND_BASE_URL;",
    "}",
    "",
  ].join("\n");
}

function tsTypeForFieldKind(kind: FieldKind): string {
  switch (kind) {
    case "text":
    case "longText":
    case "richText":
    case "email":
    case "url":
      return "string";
    case "number":
      return "number";
    case "bool":
      return "boolean";
    case "date":
      return "string";
    case "select":
      return "string";
    case "json":
      return "unknown";
    case "file":
      return "string";
    case "relation":
      return "string";
  }
  // Fallback for safety -- the switch above is exhaustive for the
  // current FieldKind union; this line satisfies TS's
  // function-must-return-on-all-paths check without an exhaustive
  // never assertion that would break if the FieldKind type widens.
  return "unknown";
}

function fieldToTsLine(field: Field): string {
  const optional = field.required ? "" : "?";
  return `  ${field.name}${optional}: ${tsTypeForFieldKind(field.kind)};`;
}

function pascalCase(input: string): string {
  return input
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((s) => s[0]!.toUpperCase() + s.slice(1))
    .join("");
}

function renderTypesTs(collections: Collection[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by @founder-os/pipeline-runner createBackendExportStep.",
    "// One interface per collection. Re-run the BACKEND stage to regenerate.",
    "",
  ];
  for (const collection of collections) {
    const name = pascalCase(collection.name);
    lines.push(`export interface ${name} {`);
    lines.push("  id: string;");
    lines.push('  created: string;');
    lines.push('  updated: string;');
    for (const field of collection.fields) {
      lines.push(fieldToTsLine(field));
    }
    lines.push("}");
    lines.push("");
  }
  if (collections.length === 0) {
    lines.push("// No collections derived yet.");
    lines.push("export {};");
  }
  return lines.join("\n");
}

function renderHooksTs(collections: Collection[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by @founder-os/pipeline-runner createBackendExportStep.",
    "// Skeletal React Query hooks per collection. BUILD wires these to",
    "// the live runtime; this layer only stubs the function signatures so",
    "// BUILD's typecheck doesn't break before the framework choice lands.",
    "",
    'import type * as Types from "./types.js";',
    "",
    "type UseQueryResult<T> = { data: T | undefined; loading: boolean; error: Error | undefined };",
    "type UseMutationResult<T> = { mutate: (input: Partial<T>) => Promise<T> };",
    "",
    "function notWired<T>(name: string): UseQueryResult<T> {",
    "  void name;",
    "  return { data: undefined, loading: false, error: undefined };",
    "}",
    "function notWiredMutation<T>(name: string): UseMutationResult<T> {",
    "  return { mutate: () => Promise.reject(new Error(`${name} not wired -- BUILD must replace this stub`)) };",
    "}",
    "",
  ];
  for (const collection of collections) {
    const typeName = pascalCase(collection.name);
    const pluralHook = `use${pascalCase(collection.name)}List`;
    const itemHook = `use${typeName}`;
    const createHook = `useCreate${typeName}`;
    lines.push(`export function ${pluralHook}(): UseQueryResult<Types.${typeName}[]> {`);
    lines.push(`  return notWired<Types.${typeName}[]>(${JSON.stringify(pluralHook)});`);
    lines.push("}");
    lines.push("");
    lines.push(`export function ${itemHook}(id: string): UseQueryResult<Types.${typeName}> {`);
    lines.push(`  void id;`);
    lines.push(`  return notWired<Types.${typeName}>(${JSON.stringify(itemHook)});`);
    lines.push("}");
    lines.push("");
    lines.push(`export function ${createHook}(): UseMutationResult<Types.${typeName}> {`);
    lines.push(`  return notWiredMutation<Types.${typeName}>(${JSON.stringify(createHook)});`);
    lines.push("}");
    lines.push("");
  }
  if (collections.length === 0) {
    lines.push("// No collections derived yet.");
    lines.push("export {};");
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Step entry point
// ---------------------------------------------------------------------------

export async function createBackendExportStep(
  ctx: CreateBackendExportContext,
): Promise<CreateBackendExportResult> {
  const notes: string[] = [];

  // Ask the provider for the canonical export.
  const exp = await ctx.provider.export(ctx.instance, ctx.collections);

  // Write backend-export.json -- the canonical artifact BUILD consumes.
  await ctx.fs.mkdir(getBackendDir(ctx.ventureRoot));
  const exportPath = getBackendExportPath(ctx.ventureRoot);
  await ctx.fs.writeFile(
    exportPath,
    `${JSON.stringify(exp, null, 2)}\n`,
  );

  // Regenerate the SDK trio. Always-emitted, even when the collection
  // list is empty -- keeps BUILD's import alias resolvable from day one.
  //
  // Branch on `exp.source` (or `exp.engine`) to pick a renderer set.
  // Supabase emits a 4th file `tables.ts` with per-collection CRUD
  // accessors; the PocketBase path stays as the original trio.
  const sdkDir = getBackendSdkDir(ctx.ventureRoot);
  await ctx.fs.mkdir(sdkDir);
  const clientPath = `${sdkDir}/client.ts`;
  const typesPath = `${sdkDir}/types.ts`;
  const hooksPath = `${sdkDir}/hooks.ts`;
  let tablesPath: string | undefined;

  if (exp.source === "supabase") {
    await ctx.fs.writeFile(clientPath, renderSupabaseClientTs(exp));
    await ctx.fs.writeFile(typesPath, renderSupabaseTypesTs(exp.collections));
    tablesPath = `${sdkDir}/tables.ts`;
    await ctx.fs.writeFile(tablesPath, renderSupabaseTablesTs(exp.collections));
    await ctx.fs.writeFile(
      hooksPath,
      renderSupabaseHooksTs(exp.collections, exp.sdk.reactHooks),
    );
    notes.push(
      `Supabase SDK emitted (client + types + tables${exp.sdk.reactHooks ? " + React Query hooks" : ""}).`,
    );
  } else {
    await ctx.fs.writeFile(clientPath, renderClientTs(exp));
    await ctx.fs.writeFile(typesPath, renderTypesTs(exp.collections));
    await ctx.fs.writeFile(hooksPath, renderHooksTs(exp.collections));
  }

  const hasLiveCollections = exp.collections.length > 0;
  if (!hasLiveCollections) {
    notes.push(
      "Provider returned 0 live collections -- SDK files emitted with placeholders only",
    );
  }

  return {
    status: "done",
    exportPath,
    sdkPaths: {
      client: clientPath,
      types: typesPath,
      hooks: hooksPath,
      ...(tablesPath ? { tables: tablesPath } : {}),
    },
    collectionCount: exp.collections.length,
    hasLiveCollections,
    notes,
  };
}
