/**
 * createBackendHooksStep -- slice 4 of backend arc.
 *
 * Reads PRODUCT_SPEC's must-priority features and turns their acceptance
 * criteria into PocketBase hook stubs at
 * `12_backend/pocketbase/pb_hooks/`. The spec doesn't have a dedicated
 * "businessRules" field today; we use the must-features' acceptance
 * criteria as the heuristic source, mirroring how the validation +
 * launch stages already lean on the feature/AC structure.
 *
 * Always-emitted hook files (matches POCKETBASE-MODULE-SPEC section 12):
 *  - 00_logging.pb.js          access log for create/update/delete
 *  - 10_business_rules.pb.js   one stub per AC -- LLM-refined when
 *                              callLlm is provided, deterministic
 *                              fallback otherwise
 *  - 99_dev_seed.pb.js         one-shot seed of 1-3 demo rows per
 *                              collection, gated on
 *                              process.env.NODE_ENV !== "production"
 *
 * Subscription-preferred LLM routing applies: when callLlm is passed,
 * the runner is responsible for routing through the subscription-mode
 * caller. This step doesn't care which provider underpins callLlm --
 * it only asks for natural-language -> hook-body conversions.
 *
 * Idempotent: re-running overwrites the hook files with the current
 * derivation. Hand-edited hooks are NOT preserved -- the user is
 * expected to commit and review every regeneration via the hooks review
 * gate that the runner emits after this step.
 */
import type { BackendProvider } from "@founder-os/backend-core";
import {
  ProductSpecCanvasSchema,
  type Feature,
  type ProductSpecCanvas,
  type VentureManifest,
} from "@founder-os/domain";
import { getSpecCanvasPath } from "@founder-os/workspace-core";

import type { Filesystem } from "../fs.js";
import type { SaasLlmCaller } from "./create-saas-research-reports.js";

export type CreateBackendHooksContext = {
  fs: Filesystem;
  manifest: VentureManifest;
  ventureRoot: string;
  provider: BackendProvider;
  /**
   * Optional LLM caller -- when provided, each business-rule stub gets
   * a one-sentence "// TODO ..." line refined via the LLM. When
   * omitted, the step emits the same stubs verbatim from the AC text.
   */
  callLlm?: SaasLlmCaller;
  runId?: string;
};

export type BackendHookStub = {
  /**
   * Feature id this stub came from, when derivable. Empty string for
   * the always-emitted hooks (logging/dev-seed).
   */
  featureId: string;
  /**
   * The AC sentence (or feature description fallback) that drove the
   * stub. Surfaced in the hook file's JSDoc comment.
   */
  source: string;
  /**
   * The hook event the stub binds to. Always
   * onRecordBeforeCreate/Update for AC-derived stubs; the always-emitted
   * hooks use other events.
   */
  event: "onRecordBeforeCreate" | "onRecordBeforeUpdate";
  /**
   * The collection name the stub binds to. Best-effort -- "" means
   * "user must pick" (the rendered hook commented out until then).
   */
  collection: string;
  /**
   * The refined hook body line (LLM output) or the deterministic
   * fallback (the raw AC sentence prefixed with "// TODO:").
   */
  bodyLine: string;
};

export type CreateBackendHooksResult = {
  status: "done";
  stubs: BackendHookStub[];
  hooksGenerated: number;
  /**
   * Disk paths of the three hook files. Always emitted.
   */
  loggingHookPath: string;
  businessRulesHookPath: string;
  devSeedHookPath: string;
  /**
   * Whether the business-rule stub bodies were LLM-refined or built
   * deterministically from AC text. The other two hook files are
   * always deterministic.
   */
  generationSource: "llm-refined" | "deterministic";
  notes: string[];
};

// ---------------------------------------------------------------------------
// Hook file synthesis
// ---------------------------------------------------------------------------

function loggingHookBody(): string {
  return [
    "// AUTO-GENERATED by @founder-os/pipeline-runner createBackendHooksStep.",
    "// Always-on access log -- visible under `pocketbase serve --dev`.",
    "// Re-run the BACKEND stage to regenerate.",
    "",
    "onRecordAfterCreateRequest((e) => {",
    "  console.log(`[create] ${e.record.collection().name} ${e.record.id}`);",
    "});",
    "",
    "onRecordAfterUpdateRequest((e) => {",
    "  console.log(`[update] ${e.record.collection().name} ${e.record.id}`);",
    "});",
    "",
    "onRecordAfterDeleteRequest((e) => {",
    "  console.log(`[delete] ${e.record.collection().name} ${e.record.id}`);",
    "});",
    "",
  ].join("\n");
}

function devSeedHookBody(): string {
  return [
    "// AUTO-GENERATED by @founder-os/pipeline-runner createBackendHooksStep.",
    "// Runs once on empty DB -- seeds 1-3 demo rows per non-auth collection",
    "// so BUILD's frontend has data to render in dev. Skipped in production",
    "// via the NODE_ENV check.",
    "// Re-run the BACKEND stage to regenerate.",
    "",
    'if ($os.getenv("NODE_ENV") !== "production") {',
    "  onAfterBootstrap((e) => {",
    "    // TODO: per-collection seed records. Slice 4 ships an empty",
    "    // template -- a follow-up will derive demo rows from PRODUCT_SPEC",
    "    // example data and BRAND voice.",
    "    console.log('[dev-seed] hook loaded; awaiting per-collection bodies');",
    "  });",
    "}",
    "",
  ].join("\n");
}

function deterministicStubBody(stub: BackendHookStub): string {
  // Strips inline newlines that would break a // single-line comment.
  const safeSource = stub.source.replace(/\s+/g, " ").trim();
  const collection = stub.collection.length > 0 ? stub.collection : "<collection>";
  return [
    `// Source: ${stub.featureId || "n/a"} -- ${safeSource}`,
    `// TODO: implement business rule for ${collection}.`,
    `${stub.event}((e) => {`,
    `  if (e.record.collection().name !== ${JSON.stringify(collection)}) return;`,
    `  // ${safeSource}`,
    "}, []);",
  ].join("\n");
}

function businessRulesHookBody(stubs: BackendHookStub[]): string {
  const header = [
    "// AUTO-GENERATED by @founder-os/pipeline-runner createBackendHooksStep.",
    "// One stub per PRODUCT_SPEC must-feature acceptance criterion. Re-run",
    "// the BACKEND stage to regenerate. Hand-edits are NOT preserved --",
    "// commit before re-running.",
    "",
  ].join("\n");

  if (stubs.length === 0) {
    return `${header}// No must-feature acceptance criteria found. Stub file kept so\n// the venture's pb_hooks/ tree stays complete.\n`;
  }

  return `${header}${stubs.map((s) => s.bodyLine).join("\n\n")}\n`;
}

// ---------------------------------------------------------------------------
// Pull must-feature ACs out of the spec canvas
// ---------------------------------------------------------------------------

type DerivedRule = {
  featureId: string;
  source: string;
  collection: string;
};

function pickCollectionForFeature(
  feature: Feature,
  collectionNames: ReadonlyArray<string>,
): string {
  const haystack = `${feature.name} ${feature.description}`.toLowerCase();
  for (const name of collectionNames) {
    if (haystack.includes(name.toLowerCase())) return name;
  }
  return "";
}

async function deriveRules(
  ctx: CreateBackendHooksContext,
): Promise<{ rules: DerivedRule[]; collectionNames: string[]; notes: string[] }> {
  const notes: string[] = [];
  const rules: DerivedRule[] = [];
  let collectionNames: string[] = [];

  const specPath = getSpecCanvasPath(ctx.ventureRoot);
  if (!(await ctx.fs.exists(specPath))) {
    notes.push("spec-canvas.json missing -- 0 business-rule stubs derived");
    return { rules, collectionNames, notes };
  }
  let canvas: ProductSpecCanvas;
  try {
    const raw = await ctx.fs.readFile(specPath);
    const parsed = ProductSpecCanvasSchema.safeParse(JSON.parse(raw));
    if (!parsed.success) {
      notes.push(
        `spec-canvas.json present but failed schema parse (${parsed.error.issues.length} issues) -- 0 stubs`,
      );
      return { rules, collectionNames, notes };
    }
    canvas = parsed.data;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    notes.push(`spec-canvas.json read/parse failed: ${msg}`);
    return { rules, collectionNames, notes };
  }

  collectionNames = canvas.dataModel.entities
    .map((e: { name: string }) => e.name)
    .filter((n: string) => n.trim().length > 0)
    .map((n: string) => n.toLowerCase());

  for (const feature of canvas.features) {
    if (feature.priority !== "must") continue;
    if (feature.name.trim().length === 0) continue;
    const collection = pickCollectionForFeature(feature, collectionNames);
    for (const ac of feature.acceptanceCriteria) {
      const trimmed = ac.trim();
      if (trimmed.length === 0) continue;
      rules.push({
        featureId: feature.id,
        source: trimmed,
        collection,
      });
    }
  }
  return { rules, collectionNames, notes };
}

// ---------------------------------------------------------------------------
// Optional LLM refinement
// ---------------------------------------------------------------------------

const LLM_SYSTEM_PROMPT = `You convert natural-language acceptance criteria into PocketBase JS hook stubs.
Output ONE valid JavaScript snippet that calls onRecordBeforeCreate or onRecordBeforeUpdate.
Keep the snippet under 20 lines. Add a leading // comment with the criterion verbatim.
If the criterion is about validation, throw new BadRequestError("...").
If the criterion is about side-effects, leave a // TODO: <action> line inside the handler.
Never invent fields the spec doesn't mention. Default to the collection name passed in. Return ONLY the JS snippet, no markdown fences.`;

async function refineWithLlm(
  callLlm: SaasLlmCaller,
  stub: BackendHookStub,
): Promise<string> {
  const user = [
    `Collection: ${stub.collection || "<unknown>"}`,
    `Feature ID: ${stub.featureId}`,
    `Acceptance criterion:`,
    stub.source,
    "",
    "Produce the hook stub snippet.",
  ].join("\n");
  try {
    const out = await callLlm({ system: LLM_SYSTEM_PROMPT, user });
    const trimmed = out.trim();
    if (trimmed.length === 0) return deterministicStubBody(stub);
    return trimmed;
  } catch {
    // Network/auth failure shouldn't break the stage -- the deterministic
    // body is a safe fallback.
    return deterministicStubBody(stub);
  }
}

// ---------------------------------------------------------------------------
// Step entry point
// ---------------------------------------------------------------------------

export async function createBackendHooksStep(
  ctx: CreateBackendHooksContext,
): Promise<CreateBackendHooksResult> {
  const { rules, notes } = await deriveRules(ctx);

  const stubs: BackendHookStub[] = rules.map((rule, idx) => ({
    featureId: rule.featureId,
    source: rule.source,
    collection: rule.collection,
    event: idx % 2 === 0 ? "onRecordBeforeCreate" : "onRecordBeforeUpdate",
    bodyLine: "", // filled in below
  }));

  const useLlm = ctx.callLlm !== undefined && stubs.length > 0;
  if (useLlm) {
    const callLlm = ctx.callLlm as SaasLlmCaller;
    // Refine sequentially -- the rules count is small and the
    // subscription-mode caller is usually not safe to parallelise.
    for (const stub of stubs) {
      stub.bodyLine = await refineWithLlm(callLlm, stub);
    }
  } else {
    for (const stub of stubs) {
      stub.bodyLine = deterministicStubBody(stub);
    }
  }

  // Path layout matches @founder-os/backend-providers/node:getPocketbasePaths.
  // We don't import that helper from the Node-only entry point because
  // pipeline-runner is loaded by the webview-side test paths too -- the
  // string literal is shorter and stays correct as long as the spec sec 3
  // layout doesn't change.
  const hooksDir = `${ctx.ventureRoot}/12_backend/pocketbase/pb_hooks`;
  await ctx.fs.mkdir(hooksDir);

  const loggingHookPath = `${hooksDir}/00_logging.pb.js`;
  const businessRulesHookPath = `${hooksDir}/10_business_rules.pb.js`;
  const devSeedHookPath = `${hooksDir}/99_dev_seed.pb.js`;

  await ctx.fs.writeFile(loggingHookPath, loggingHookBody());
  await ctx.fs.writeFile(businessRulesHookPath, businessRulesHookBody(stubs));
  await ctx.fs.writeFile(devSeedHookPath, devSeedHookBody());

  return {
    status: "done",
    stubs,
    hooksGenerated: stubs.length,
    loggingHookPath,
    businessRulesHookPath,
    devSeedHookPath,
    generationSource: useLlm ? "llm-refined" : "deterministic",
    notes,
  };
}
