import { createLogger } from "@founder-os/logger";
import { getBriefDir } from "@founder-os/workspace-core";
import type { RunStep } from "@founder-os/pipeline-core";
import type { Filesystem } from "../fs.js";

const log = createLogger("pipeline-runner:ensure-brief");

export type EnsureBriefContext = {
  fs: Filesystem;
  ventureId: string;
  ventureRoot: string;
  ventureName: string;
  appType: string;
  industry?: string;
};

export async function ensureBriefStep(ctx: EnsureBriefContext): Promise<Partial<RunStep>> {
  const briefDir = getBriefDir(ctx.ventureRoot);
  await ctx.fs.mkdir(briefDir);

  const briefPath = `${briefDir}/dev-brief.md`;

  if (await ctx.fs.exists(briefPath)) {
    log.info(`Brief already exists at ${briefPath}, skipping generation`);
    return { status: "skipped", producedArtifactIds: [] };
  }

  const brief = generateDefaultBrief(ctx);
  await ctx.fs.writeFile(briefPath, brief);
  log.info(`Created dev brief at ${briefPath}`);

  return {
    status: "done",
    completedAt: new Date().toISOString(),
    producedArtifactIds: [],
  };
}

function generateDefaultBrief(ctx: EnsureBriefContext): string {
  return `# Development Brief — ${ctx.ventureName}

## Overview
- **Venture**: ${ctx.ventureName}
- **App Type**: ${ctx.appType}
- **Industry**: ${ctx.industry ?? "General"}

## Problem Statement
_To be completed by the founder._

## Target Users
_Who is this for? What jobs do they need done?_

## Core Features (MVP)
1. Feature 1
2. Feature 2
3. Feature 3

## Technical Constraints
- [ ] Mobile-first
- [ ] Offline capable
- [ ] Multi-tenant

## Success Metrics
- _Define what success looks like in 30/60/90 days_

---
_Generated by Founder OS on ${new Date().toISOString()}_
`;
}
