/**
 * Supabase BUILD codegen -- slice 6 of the Supabase arc.
 *
 * Emits per-venture client + tables + hooks TS files when
 * `BackendExport.source === "supabase"`. The non-Supabase path stays
 * in `create-backend-export.ts` and uses the PocketBase-flavoured
 * renderers; this module is only consumed when the backend stage
 * resolved Supabase.
 *
 * File shape per SUPABASE-MODULE-SPEC.md sec 6:
 *
 *   12_backend/sdk/
 *   ├── client.ts          createClient singleton + env-var resolution
 *   ├── types.ts           Database type + per-collection Row/Insert/Update
 *   ├── tables.ts          per-collection list/view/create/update/delete
 *   └── hooks.ts           React Query hooks (gated on sdk.reactHooks)
 *
 * The emitted files import from `@supabase/supabase-js` and (optionally)
 * `@tanstack/react-query`. BUILD\'s package.json scaffolding adds those
 * dependencies; the BACKEND stage just emits the TS that references them.
 *
 * Pure rendering -- no IO. The step caller in create-backend-export.ts
 * decides which renderer set to use based on `exp.source`.
 */

import type { BackendExport, Collection, Field, FieldKind } from "@founder-os/backend-core";

// ---------------------------------------------------------------------------
// FieldKind -> TS type (mirrors the PocketBase-side mapping but uses
// `string | null` for nullable optionals to align with the Postgres
// Row/Insert/Update shape supabase-js generates)
// ---------------------------------------------------------------------------

function tsTypeForFieldKind(kind: FieldKind): string {
  switch (kind) {
    case "text":
    case "longText":
    case "richText":
    case "email":
    case "url":
    case "date":
    case "select":
    case "file":
    case "relation":
      return "string";
    case "number":
      return "number";
    case "bool":
      return "boolean";
    case "json":
      return "unknown";
  }
}

function fieldRowType(field: Field): string {
  const t = tsTypeForFieldKind(field.kind);
  // Nullable when not required (matches the Postgres default of NULL
  // when required=false). `gen_random_uuid()` etc handle id/created_at.
  return field.required ? t : `${t} | null`;
}

function pascalCase(input: string): string {
  return input
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((s) => s[0]!.toUpperCase() + s.slice(1))
    .join("");
}

// ---------------------------------------------------------------------------
// client.ts -- createClient singleton
// ---------------------------------------------------------------------------

export function renderSupabaseClientTs(exp: BackendExport): string {
  return [
    "// AUTO-GENERATED by @founder-os/pipeline-runner (Supabase BUILD codegen).",
    "// Re-run the BACKEND stage to regenerate. BUILD imports this via the",
    "// `@/lib/backend` alias mapped in tsconfig.",
    "",
    `import { createClient, type SupabaseClient } from "@supabase/supabase-js";`,
    `import type { Database } from "./types.js";`,
    "",
    `export const BACKEND_ENGINE = ${JSON.stringify(exp.engine)};`,
    `export const SUPABASE_PROJECT_URL = ${JSON.stringify(exp.baseUrl)};`,
    "",
    "/**",
    " * Resolve URL + anon key from Vite env at runtime. The BUILD scaffold",
    " * MUST set both in .env.local; the BACKEND stage emits these as the",
    " * names a vite-based BUILD recognises.",
    " */",
    "function resolveEnv(): { url: string; anonKey: string } {",
    "  const env =",
    "    typeof import.meta !== \"undefined\"",
    "      ? ((import.meta as { env?: Record<string, string> }).env ?? {})",
    "      : {};",
    "  const url = env.VITE_SUPABASE_URL ?? SUPABASE_PROJECT_URL;",
    "  const anonKey = env.VITE_SUPABASE_ANON_KEY ?? \"\";",
    "  if (!url || !anonKey) {",
    "    throw new Error(",
    "      \"VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set in \" +",
    "        \".env.local for the BUILD output to connect to Supabase.\"",
    "    );",
    "  }",
    "  return { url, anonKey };",
    "}",
    "",
    "let _client: SupabaseClient<Database> | null = null;",
    "",
    "/**",
    " * Lazily-instantiated singleton. Subsequent calls return the same",
    " * client so React component trees share state and realtime sockets.",
    " */",
    "export function getSupabase(): SupabaseClient<Database> {",
    "  if (_client) return _client;",
    "  const { url, anonKey } = resolveEnv();",
    "  _client = createClient<Database>(url, anonKey);",
    "  return _client;",
    "}",
    "",
    "// Convenience -- the SDK conventions across the codebase favour a",
    "// named `supabase` export rather than a getter. Both work.",
    "export const supabase = new Proxy({} as SupabaseClient<Database>, {",
    "  get(_target, prop) {",
    "    return (getSupabase() as unknown as Record<string, unknown>)[prop as string];",
    "  },",
    "});",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// types.ts -- Database type + per-collection Row/Insert/Update
// ---------------------------------------------------------------------------

function renderRowType(collection: Collection): string {
  const lines: string[] = [];
  lines.push(`export type ${pascalCase(collection.name)}Row = {`);
  lines.push("  id: string;");
  lines.push("  created_at: string;");
  lines.push("  updated_at: string;");
  for (const field of collection.fields) {
    lines.push(`  ${field.name}: ${fieldRowType(field)};`);
  }
  lines.push("};");
  return lines.join("\n");
}

function renderInsertType(collection: Collection): string {
  const lines: string[] = [];
  lines.push(`export type ${pascalCase(collection.name)}Insert = {`);
  // id / timestamps optional on insert -- Postgres defaults fill them.
  lines.push("  id?: string;");
  lines.push("  created_at?: string;");
  lines.push("  updated_at?: string;");
  for (const field of collection.fields) {
    const optional = field.required ? "" : "?";
    lines.push(`  ${field.name}${optional}: ${tsTypeForFieldKind(field.kind)};`);
  }
  lines.push("};");
  return lines.join("\n");
}

function renderUpdateType(collection: Collection): string {
  const lines: string[] = [];
  lines.push(`export type ${pascalCase(collection.name)}Update = {`);
  // every field optional on update.
  lines.push("  id?: string;");
  lines.push("  created_at?: string;");
  lines.push("  updated_at?: string;");
  for (const field of collection.fields) {
    lines.push(`  ${field.name}?: ${tsTypeForFieldKind(field.kind)};`);
  }
  lines.push("};");
  return lines.join("\n");
}

export function renderSupabaseTypesTs(collections: Collection[]): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @founder-os/pipeline-runner (Supabase BUILD codegen).");
  lines.push("// Database type follows the shape supabase-js expects so the");
  lines.push("// SupabaseClient<Database> generic narrows .from(\"<name>\") correctly.");
  lines.push("");

  if (collections.length === 0) {
    lines.push("// No collections derived yet -- BUILD will compile but");
    lines.push("// supabase.from(\"...\") will be untyped until the BACKEND stage runs.");
    lines.push("export type Database = {");
    lines.push("  public: {");
    lines.push("    Tables: Record<string, never>;");
    lines.push("    Views: Record<string, never>;");
    lines.push("    Functions: Record<string, never>;");
    lines.push("    Enums: Record<string, never>;");
    lines.push("    CompositeTypes: Record<string, never>;");
    lines.push("  };");
    lines.push("};");
    return lines.join("\n");
  }

  // Per-collection Row / Insert / Update types.
  for (const c of collections) {
    lines.push(renderRowType(c));
    lines.push("");
    lines.push(renderInsertType(c));
    lines.push("");
    lines.push(renderUpdateType(c));
    lines.push("");
  }

  // Database type assembling everything in `public.Tables`.
  lines.push("export type Database = {");
  lines.push("  public: {");
  lines.push("    Tables: {");
  for (const c of collections) {
    const P = pascalCase(c.name);
    lines.push(`      ${c.name}: {`);
    lines.push(`        Row: ${P}Row;`);
    lines.push(`        Insert: ${P}Insert;`);
    lines.push(`        Update: ${P}Update;`);
    lines.push("      };");
  }
  lines.push("    };");
  lines.push("    Views: Record<string, never>;");
  lines.push("    Functions: Record<string, never>;");
  lines.push("    Enums: Record<string, never>;");
  lines.push("    CompositeTypes: Record<string, never>;");
  lines.push("  };");
  lines.push("};");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// tables.ts -- per-collection list/view/create/update/delete helpers
// ---------------------------------------------------------------------------

export function renderSupabaseTablesTs(collections: Collection[]): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @founder-os/pipeline-runner (Supabase BUILD codegen).");
  lines.push("// Per-collection typed accessors. Each helper returns the raw");
  lines.push("// PostgrestSingleResponse / PostgrestResponse so callers can");
  lines.push("// destructure {data, error} per supabase-js convention.");
  lines.push("");
  lines.push("import { supabase } from \"./client.js\";");
  lines.push("import type {");
  for (const c of collections) {
    const P = pascalCase(c.name);
    lines.push(`  ${P}Insert,`);
    lines.push(`  ${P}Update,`);
  }
  lines.push("} from \"./types.js\";");
  lines.push("");
  if (collections.length === 0) {
    lines.push("// No collections derived yet.");
    lines.push("export {};");
    return lines.join("\n");
  }

  for (const c of collections) {
    const P = pascalCase(c.name);
    lines.push(`export const ${c.name} = {`);
    lines.push(`  list: () => supabase.from(${JSON.stringify(c.name)}).select(\"*\"),`);
    lines.push(`  view: (id: string) =>`);
    lines.push(`    supabase.from(${JSON.stringify(c.name)}).select(\"*\").eq(\"id\", id).single(),`);
    lines.push(`  create: (input: ${P}Insert) =>`);
    lines.push(`    supabase.from(${JSON.stringify(c.name)}).insert(input).select().single(),`);
    lines.push(`  update: (id: string, patch: ${P}Update) =>`);
    lines.push(`    supabase.from(${JSON.stringify(c.name)}).update(patch).eq(\"id\", id).select().single(),`);
    lines.push(`  delete: (id: string) =>`);
    lines.push(`    supabase.from(${JSON.stringify(c.name)}).delete().eq(\"id\", id),`);
    lines.push("} as const;");
    lines.push("");
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// hooks.ts -- React Query hooks (gated on sdk.reactHooks)
// ---------------------------------------------------------------------------

export function renderSupabaseHooksTs(
  collections: Collection[],
  reactHooks: boolean,
): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @founder-os/pipeline-runner (Supabase BUILD codegen).");

  if (!reactHooks) {
    // Without reactHooks, BUILD\'s framework isn\'t React-via-RQ. Emit
    // empty re-exports so any code that imports `./hooks` doesn\'t crash.
    lines.push("// React Query hooks not emitted -- BACKEND export sdk.reactHooks=false.");
    lines.push("// Use `./tables` directly for queries; wire your framework\'s data");
    lines.push("// layer (SWR / TanStack Router loaders / Solid resources) on top.");
    lines.push("export {};");
    return lines.join("\n");
  }

  lines.push("// React Query hooks per collection. Wraps the `./tables`");
  lines.push("// helpers and unwraps {data, error} into the hook return shape.");
  lines.push("");
  lines.push("import { useQuery, useMutation, useQueryClient } from \"@tanstack/react-query\";");
  lines.push("import * as tables from \"./tables.js\";");
  lines.push("import type {");
  for (const c of collections) {
    const P = pascalCase(c.name);
    lines.push(`  ${P}Insert,`);
    lines.push(`  ${P}Update,`);
  }
  lines.push("} from \"./types.js\";");
  lines.push("");

  for (const c of collections) {
    const P = pascalCase(c.name);
    const camelName = c.name;

    // Use<Name>List
    lines.push(`export function use${P}List() {`);
    lines.push("  return useQuery({");
    lines.push(`    queryKey: [${JSON.stringify(camelName)}],`);
    lines.push("    queryFn: async () => {");
    lines.push(`      const { data, error } = await tables.${camelName}.list();`);
    lines.push("      if (error) throw error;");
    lines.push("      return data;");
    lines.push("    },");
    lines.push("  });");
    lines.push("}");
    lines.push("");

    // Use<Name>
    lines.push(`export function use${P}(id: string) {`);
    lines.push("  return useQuery({");
    lines.push(`    queryKey: [${JSON.stringify(camelName)}, id],`);
    lines.push("    queryFn: async () => {");
    lines.push(`      const { data, error } = await tables.${camelName}.view(id);`);
    lines.push("      if (error) throw error;");
    lines.push("      return data;");
    lines.push("    },");
    lines.push("    enabled: id.length > 0,");
    lines.push("  });");
    lines.push("}");
    lines.push("");

    // Create
    lines.push(`export function useCreate${P}() {`);
    lines.push("  const qc = useQueryClient();");
    lines.push("  return useMutation({");
    lines.push(`    mutationFn: async (input: ${P}Insert) => {`);
    lines.push(`      const { data, error } = await tables.${camelName}.create(input);`);
    lines.push("      if (error) throw error;");
    lines.push("      return data;");
    lines.push("    },");
    lines.push(`    onSuccess: () => qc.invalidateQueries({ queryKey: [${JSON.stringify(camelName)}] }),`);
    lines.push("  });");
    lines.push("}");
    lines.push("");

    // Update
    lines.push(`export function useUpdate${P}() {`);
    lines.push("  const qc = useQueryClient();");
    lines.push("  return useMutation({");
    lines.push(`    mutationFn: async (args: { id: string; patch: ${P}Update }) => {`);
    lines.push(`      const { data, error } = await tables.${camelName}.update(args.id, args.patch);`);
    lines.push("      if (error) throw error;");
    lines.push("      return data;");
    lines.push("    },");
    lines.push(`    onSuccess: () => qc.invalidateQueries({ queryKey: [${JSON.stringify(camelName)}] }),`);
    lines.push("  });");
    lines.push("}");
    lines.push("");

    // Delete
    lines.push(`export function useDelete${P}() {`);
    lines.push("  const qc = useQueryClient();");
    lines.push("  return useMutation({");
    lines.push("    mutationFn: async (id: string) => {");
    lines.push(`      const { error } = await tables.${camelName}.delete(id);`);
    lines.push("      if (error) throw error;");
    lines.push("    },");
    lines.push(`    onSuccess: () => qc.invalidateQueries({ queryKey: [${JSON.stringify(camelName)}] }),`);
    lines.push("  });");
    lines.push("}");
    lines.push("");
  }
  return lines.join("\n");
}
