/**
 * Project lifecycle helpers for the venture's PocketBase folder.
 *
 * The shape we land here matches spec sec 3 exactly:
 *
 *   <ventureRoot>/12_backend/pocketbase/
 *     pocketbase(.exe)
 *     pb_data/
 *     pb_migrations/
 *       1747000000_init_users.js
 *       1747000100_init_collections.js
 *       1747000200_init_api_rules.js
 *     pb_hooks/
 *       00_logging.pb.js
 *       10_business_rules.pb.js
 *       99_dev_seed.pb.js
 *     README.md
 *
 * Slice 2 ships the path helpers + a deterministic migration writer
 * (used by applySchema() in pocketbase-provider.ts). Slice 4 builds on
 * this to translate PRODUCT_SPEC entities into actual migration JS;
 * slice 2 just locks the file-naming + writer contract.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { Collection } from "@founder-os/backend-core";

import { resolveBinaryPath } from "./binary.js";

// ---------------------------------------------------------------------------
// Path layout
// ---------------------------------------------------------------------------

export type PocketbasePaths = {
  ventureRoot: string;
  dir: string;
  binaryPath: string;
  dataDir: string;
  migrationsDir: string;
  hooksDir: string;
  sdkDir: string;
  readmePath: string;
};

export function getPocketbasePaths(ventureRoot: string): PocketbasePaths {
  const dir = join(ventureRoot, "12_backend", "pocketbase");
  return {
    ventureRoot,
    dir,
    binaryPath: resolveBinaryPath(ventureRoot),
    dataDir: join(dir, "pb_data"),
    migrationsDir: join(dir, "pb_migrations"),
    hooksDir: join(dir, "pb_hooks"),
    sdkDir: join(ventureRoot, "12_backend", "sdk"),
    readmePath: join(dir, "README.md"),
  };
}

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------

export type BootstrapOpts = {
  ventureRoot: string;
  /**
   * Optional fs injection for tests. Defaults to node:fs/promises.
   */
  mkdirImpl?: typeof mkdir;
  writeFileImpl?: typeof writeFile;
};

/**
 * Creates the directory skeleton for a fresh venture's PocketBase.
 * Idempotent -- safe to call on every provision().
 *
 * Does NOT download the binary (see binary.ts). Does NOT write any
 * migrations beyond the directories -- applySchema() handles that.
 */
export async function bootstrapPocketbaseProject(
  opts: BootstrapOpts
): Promise<PocketbasePaths> {
  const paths = getPocketbasePaths(opts.ventureRoot);
  const mkdirAsync = opts.mkdirImpl ?? mkdir;

  await mkdirAsync(paths.dir, { recursive: true });
  await mkdirAsync(paths.dataDir, { recursive: true });
  await mkdirAsync(paths.migrationsDir, { recursive: true });
  await mkdirAsync(paths.hooksDir, { recursive: true });
  await mkdirAsync(paths.sdkDir, { recursive: true });

  return paths;
}

// ---------------------------------------------------------------------------
// Migration writer
// ---------------------------------------------------------------------------

export type WriteMigrationOpts = {
  migrationsDir: string;
  /**
   * Lowercase snake_case name. Becomes "<timestamp>_<name>.js" on disk.
   */
  name: string;
  /**
   * Full JS body. Caller is responsible for the migrate().up/.down shape;
   * this function does no synthesis. Slice 4 supplies a builder.
   */
  body: string;
  /**
   * Optional clock injection. Defaults to Date.now(). Tests pin this so
   * the on-disk filename is deterministic.
   */
  now?: () => number;
  writeFileImpl?: typeof writeFile;
};

export async function writeMigration(
  opts: WriteMigrationOpts
): Promise<{ path: string; filename: string }> {
  const ts = (opts.now ?? Date.now)();
  const safeName = opts.name.replace(/[^a-z0-9_]/gi, "_").toLowerCase();
  const filename = `${ts}_${safeName}.js`;
  const target = join(opts.migrationsDir, filename);
  const writer = opts.writeFileImpl ?? writeFile;
  await writer(target, opts.body, "utf8");
  return { path: target, filename };
}

// ---------------------------------------------------------------------------
// Skeletal migration synthesis
// ---------------------------------------------------------------------------

/**
 * Generates a minimal migrate({up,down}) wrapper around an addCollection
 * call. Slice 2 keeps the body literal; slice 4 promotes this to a
 * full field-by-field PB schema generator.
 *
 * Exported here (not in pocketbase-provider) so the migration writer
 * can be unit-tested without spinning up a provider.
 */
export function buildSkeletalCollectionMigration(
  collection: Collection
): string {
  const json = JSON.stringify({ name: collection.name, type: collection.type }, null, 2);
  return [
    "// AUTO-GENERATED by @founder-os/backend-providers slice 2 (skeletal).",
    "// Slice 4 promotes this to a full schema-aware generator.",
    "migrate(",
    "  (db) => {",
    `    const collection = new Collection(${json});`,
    "    return db.save(collection);",
    "  },",
    `  (db) => db.delete(db.collection(${JSON.stringify(collection.name)}))`,
    ");",
    "",
  ].join("\n");
}
