// @founder-os/handoff-pack-core/manifest -- the canonical 200+ entry document
// manifest. Every PDF that lands in 13_handoff_pack/ corresponds to one entry.
//
// Authored by slice 1 of the handoff-pack arc. Mirrors the brief's section A-O
// layout flattened into 11 audience folders (00-company-control through
// 10-templates). Tier field per spec sec 4:
//   A: Golden 15 -- LLM-generated from existing stage outputs.
//   B: Extended ~30 -- LLM-generated, lower fidelity.
//   C: Partial-stub -- placeholders filled from pipeline + brand + manifest.
//   D: Pure stub -- branded blank with TODO callouts.
//
// Run computeManifestStats() in src/index.ts? -- no, the test suite (slice 2)
// asserts the per-tier and per-category counts so drift here is caught.

import type { DocDescriptor } from "./index.js";

export const DOC_MANIFEST: ReadonlyArray<DocDescriptor> = [
  // -------- 00-company-control --------
  { id: "company-brief", category: "00-company-control", slot: "00", title: "Company Brief", description: "One-page overview of the company, market, product, and goals.", tier: "A", roles: ["founder", "dev", "designer", "marketing", "sales", "support", "finance", "contractor"], sourceStages: ["RESEARCH", "BRAND"], templatePath: "00-company-control/00-company-brief.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "MISSION", "TARGET_MARKET", "PRODUCT_SUMMARY", "BUSINESS_MODEL", "CURRENT_DATE"] },
  { id: "founder-vision", category: "00-company-control", slot: "01", title: "Founder Vision Document", description: "The founder's long-term vision, values, and non-negotiables.", tier: "B", roles: ["founder"], sourceStages: ["RESEARCH"], templatePath: "00-company-control/01-founder-vision.md.hbs", placeholders: ["COMPANY_NAME", "FOUNDER_NAME", "VISION", "VALUES", "CURRENT_DATE"] },
  { id: "company-register", category: "00-company-control", slot: "02", title: "Company Register", description: "Registered office, directors, shareholders, PSCs, Companies House refs.", tier: "C", roles: ["founder", "finance"], sourceStages: ["UK_SETUP"], templatePath: "00-company-control/02-company-register.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_NUMBER", "REGISTERED_OFFICE", "DIRECTORS", "PSCS", "CURRENT_DATE"] },
  { id: "cap-table", category: "00-company-control", slot: "03", title: "Cap Table", description: "Founder + investor + employee equity holdings, vesting cliffs, share class.", tier: "D", roles: ["founder", "finance"], sourceStages: [], templatePath: "00-company-control/03-cap-table.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "shareholder-agreement", category: "00-company-control", slot: "04", title: "Shareholder Agreement", description: "Founder shares, vesting, decision rights, drag/tag rights, exit terms.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "00-company-control/04-shareholder-agreement.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "articles-of-association", category: "00-company-control", slot: "05", title: "Articles of Association", description: "The company's constitutional rules.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "00-company-control/05-articles-of-association.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "director-register", category: "00-company-control", slot: "06", title: "Director and Officer Register", description: "Directors, company secretary, persons with significant control.", tier: "D", roles: ["founder", "finance"], sourceStages: [], templatePath: "00-company-control/06-director-register.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "board-decision-log", category: "00-company-control", slot: "07", title: "Board Decision Log", description: "Record of major company decisions with rationale and date.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "00-company-control/07-board-decision-log.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "founder-agreement", category: "00-company-control", slot: "08", title: "Founder Agreement", description: "Founder roles, equity, IP assignment, vesting, leaving rules.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "00-company-control/08-founder-agreement.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "ip-assignment-agreement", category: "00-company-control", slot: "09", title: "Intellectual Property Assignment", description: "Ensures code, designs, brand assets, and inventions belong to the company.", tier: "D", roles: ["founder", "dev", "designer", "contractor"], sourceStages: [], templatePath: "00-company-control/09-ip-assignment-agreement.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "company-asset-register", category: "00-company-control", slot: "10", title: "Company Asset Register", description: "Laptops, software licences, domains, repositories, hardware.", tier: "D", roles: ["founder", "finance"], sourceStages: [], templatePath: "00-company-control/10-company-asset-register.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "domain-account-register", category: "00-company-control", slot: "11", title: "Domain and Account Register", description: "Domains, hosting, admin emails, SaaS tools, billing owners.", tier: "D", roles: ["founder", "dev", "finance"], sourceStages: [], templatePath: "00-company-control/11-domain-account-register.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "insurance-file", category: "00-company-control", slot: "12", title: "Insurance File", description: "Professional indemnity, cyber, public liability, employers' liability.", tier: "D", roles: ["founder", "finance"], sourceStages: [], templatePath: "00-company-control/12-insurance-file.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "risk-register", category: "00-company-control", slot: "13", title: "Risk Register", description: "Legal, product, financial, security, market, operational, people risks.", tier: "B", roles: ["founder"], sourceStages: ["AUDIT", "FINANCE", "RESEARCH"], templatePath: "00-company-control/13-risk-register.md.hbs", placeholders: ["COMPANY_NAME", "RISKS_BY_CATEGORY", "CURRENT_DATE"] },
  { id: "tool-stack-register", category: "00-company-control", slot: "14", title: "Tool Stack Register", description: "All tools used, owners, costs, renewal dates.", tier: "D", roles: ["founder", "dev", "finance"], sourceStages: [], templatePath: "00-company-control/14-tool-stack-register.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 01-strategy --------
  { id: "business-plan", category: "01-strategy", slot: "00", title: "Business Plan", description: "How the company will make money, grow, and survive.", tier: "B", roles: ["founder", "finance"], sourceStages: ["RESEARCH", "FINANCE", "VALIDATION"], templatePath: "01-strategy/00-business-plan.md.hbs", placeholders: ["COMPANY_NAME", "MARKET", "REVENUE_MODEL", "UNIT_ECONOMICS", "TEAM_PLAN", "CURRENT_DATE"] },
  { id: "market-research", category: "01-strategy", slot: "01", title: "Market Research Report", description: "Market size, trends, customer pain points, opportunity.", tier: "A", roles: ["founder", "marketing", "sales"], sourceStages: ["RESEARCH"], templatePath: "01-strategy/01-market-research.md.hbs", placeholders: ["COMPANY_NAME", "MARKET_SIZE", "TRENDS", "PAIN_POINTS", "OPPORTUNITY", "CURRENT_DATE"] },
  { id: "competitor-analysis", category: "01-strategy", slot: "02", title: "Competitor Analysis", description: "Feature comparison, pricing, positioning, weaknesses.", tier: "B", roles: ["founder", "marketing", "sales"], sourceStages: ["RESEARCH"], templatePath: "01-strategy/02-competitor-analysis.md.hbs", placeholders: ["COMPANY_NAME", "COMPETITORS", "CURRENT_DATE"] },
  { id: "icp-personas", category: "01-strategy", slot: "03", title: "ICP and Buyer Personas", description: "Ideal customer profile, decision maker, user, influencer, blocker.", tier: "A", roles: ["founder", "sales", "marketing", "designer"], sourceStages: ["VALIDATION", "CRM"], templatePath: "01-strategy/03-icp-personas.md.hbs", placeholders: ["COMPANY_NAME", "ICP", "PERSONAS", "CURRENT_DATE"] },
  { id: "pricing-strategy", category: "01-strategy", slot: "04", title: "Pricing Strategy", description: "Free tier, paid tiers, enterprise, discounts, usage limits.", tier: "B", roles: ["founder", "finance", "sales"], sourceStages: ["VALIDATION", "FINANCE"], templatePath: "01-strategy/04-pricing-strategy.md.hbs", placeholders: ["COMPANY_NAME", "PRICING_TIERS", "CURRENT_DATE"] },
  { id: "business-model-canvas", category: "01-strategy", slot: "05", title: "Business Model Canvas", description: "Customers, value props, channels, revenue, costs, partners.", tier: "B", roles: ["founder"], sourceStages: ["RESEARCH", "VALIDATION"], templatePath: "01-strategy/05-business-model-canvas.md.hbs", placeholders: ["COMPANY_NAME", "CANVAS", "CURRENT_DATE"] },
  { id: "swot-analysis", category: "01-strategy", slot: "06", title: "SWOT Analysis", description: "Strengths, weaknesses, opportunities, threats.", tier: "C", roles: ["founder"], sourceStages: ["RESEARCH"], templatePath: "01-strategy/06-swot-analysis.md.hbs", placeholders: ["COMPANY_NAME", "STRENGTHS", "WEAKNESSES", "OPPORTUNITIES", "THREATS", "CURRENT_DATE"] },
  { id: "positioning-statement", category: "01-strategy", slot: "07", title: "Positioning Statement", description: "Who the product is for and why it is different.", tier: "B", roles: ["founder", "marketing"], sourceStages: ["BRAND", "VALIDATION"], templatePath: "01-strategy/07-positioning-statement.md.hbs", placeholders: ["COMPANY_NAME", "POSITIONING", "CURRENT_DATE"] },
  { id: "value-proposition", category: "01-strategy", slot: "08", title: "Value Proposition Document", description: "Core promise to customers.", tier: "B", roles: ["founder", "marketing", "sales"], sourceStages: ["BRAND", "VALIDATION"], templatePath: "01-strategy/08-value-proposition.md.hbs", placeholders: ["COMPANY_NAME", "VALUE_PROPS", "CURRENT_DATE"] },
  { id: "strategic-roadmap", category: "01-strategy", slot: "09", title: "Strategic Roadmap", description: "3-month, 6-month, 12-month goals.", tier: "B", roles: ["founder"], sourceStages: ["PRODUCT_SPEC", "AUDIT"], templatePath: "01-strategy/09-strategic-roadmap.md.hbs", placeholders: ["COMPANY_NAME", "HORIZONS", "CURRENT_DATE"] },
  { id: "okrs-kpis", category: "01-strategy", slot: "10", title: "OKRs and KPIs", description: "Objectives and measurable results.", tier: "C", roles: ["founder"], sourceStages: [], templatePath: "01-strategy/10-okrs-kpis.md.hbs", placeholders: ["COMPANY_NAME", "OKRS", "KPIS", "CURRENT_DATE"] },
  { id: "unit-economics-model", category: "01-strategy", slot: "11", title: "Unit Economics Model", description: "CAC, LTV, churn, gross margin, hosting cost, API cost, support cost.", tier: "B", roles: ["founder", "finance"], sourceStages: ["FINANCE", "CRM"], templatePath: "01-strategy/11-unit-economics-model.md.hbs", placeholders: ["COMPANY_NAME", "CAC", "LTV", "CHURN", "MARGINS", "CURRENT_DATE"] },
  { id: "milestone-plan", category: "01-strategy", slot: "12", title: "Milestone Plan", description: "What must be achieved before launch, funding, hiring, scaling.", tier: "C", roles: ["founder"], sourceStages: ["PRODUCT_SPEC", "FINANCE"], templatePath: "01-strategy/12-milestone-plan.md.hbs", placeholders: ["COMPANY_NAME", "MILESTONES", "CURRENT_DATE"] },
  { id: "investor-deck", category: "01-strategy", slot: "13", title: "Investor / Funding Deck", description: "Problem, solution, market, traction, team, financials.", tier: "B", roles: ["founder"], sourceStages: ["RESEARCH", "FINANCE", "BRAND"], templatePath: "01-strategy/13-investor-deck.md.hbs", placeholders: ["COMPANY_NAME", "PROBLEM", "SOLUTION", "MARKET", "TRACTION", "TEAM", "ASK", "CURRENT_DATE"] },
  { id: "north-star-metric", category: "01-strategy", slot: "14", title: "North Star Metric", description: "Main metric that defines product success.", tier: "C", roles: ["founder"], sourceStages: ["PRODUCT_SPEC"], templatePath: "01-strategy/14-north-star-metric.md.hbs", placeholders: ["COMPANY_NAME", "NORTH_STAR", "CURRENT_DATE"] },

  // -------- 02-product --------
  { id: "product-vision", category: "02-product", slot: "00", title: "Product Vision", description: "Product purpose and long-term direction.", tier: "B", roles: ["founder", "dev", "designer", "marketing"], sourceStages: ["PRODUCT_SPEC", "BRAND"], templatePath: "02-product/00-product-vision.md.hbs", placeholders: ["COMPANY_NAME", "PRODUCT_NAME", "VISION", "CURRENT_DATE"] },
  { id: "prd", category: "02-product", slot: "01", title: "Product Requirements Document", description: "Features, user needs, acceptance criteria, constraints.", tier: "A", roles: ["founder", "dev", "designer"], sourceStages: ["PRODUCT_SPEC"], templatePath: "02-product/01-prd.md.hbs", placeholders: ["COMPANY_NAME", "PRODUCT_NAME", "FEATURES", "ACCEPTANCE_CRITERIA", "CURRENT_DATE"] },
  { id: "mvp-scope", category: "02-product", slot: "02", title: "MVP Scope Document", description: "What version 1 includes, what is excluded, what comes later.", tier: "A", roles: ["founder", "dev", "designer"], sourceStages: ["PRODUCT_SPEC"], templatePath: "02-product/02-mvp-scope.md.hbs", placeholders: ["COMPANY_NAME", "IN_SCOPE", "OUT_OF_SCOPE", "LATER", "CURRENT_DATE"] },
  { id: "user-stories", category: "02-product", slot: "03", title: "User Stories", description: "'As a user, I want to...' requirements.", tier: "A", roles: ["dev", "designer"], sourceStages: ["PRODUCT_SPEC"], templatePath: "02-product/03-user-stories.md.hbs", placeholders: ["COMPANY_NAME", "STORIES", "CURRENT_DATE"] },
  { id: "user-flows", category: "02-product", slot: "04", title: "User Flow Diagrams", description: "How users move through the product.", tier: "B", roles: ["dev", "designer"], sourceStages: ["WIREFRAME"], templatePath: "02-product/04-user-flows.md.hbs", placeholders: ["COMPANY_NAME", "FLOWS", "CURRENT_DATE"] },
  { id: "user-journey-maps", category: "02-product", slot: "05", title: "User Journey Maps", description: "Step-by-step customer experience across touchpoints.", tier: "C", roles: ["designer", "marketing", "support"], sourceStages: ["VALIDATION", "CRM"], templatePath: "02-product/05-user-journey-maps.md.hbs", placeholders: ["COMPANY_NAME", "PERSONAS", "JOURNEYS", "CURRENT_DATE"] },
  { id: "feature-list", category: "02-product", slot: "06", title: "Feature List", description: "Full backlog of possible features.", tier: "C", roles: ["founder", "dev"], sourceStages: ["PRODUCT_SPEC", "AUDIT"], templatePath: "02-product/06-feature-list.md.hbs", placeholders: ["COMPANY_NAME", "FEATURES", "CURRENT_DATE"] },
  { id: "feature-priority-matrix", category: "02-product", slot: "07", title: "Feature Priority Matrix", description: "Must-have, should-have, could-have, later.", tier: "C", roles: ["founder", "dev"], sourceStages: ["PRODUCT_SPEC"], templatePath: "02-product/07-feature-priority-matrix.md.hbs", placeholders: ["COMPANY_NAME", "MOSCOW", "CURRENT_DATE"] },
  { id: "acceptance-criteria", category: "02-product", slot: "08", title: "Acceptance Criteria", description: "Conditions for a feature to be considered complete.", tier: "C", roles: ["dev"], sourceStages: ["PRODUCT_SPEC"], templatePath: "02-product/08-acceptance-criteria.md.hbs", placeholders: ["COMPANY_NAME", "CRITERIA_BY_FEATURE", "CURRENT_DATE"] },
  { id: "product-roadmap", category: "02-product", slot: "09", title: "Product Roadmap", description: "Planned product evolution over time.", tier: "B", roles: ["founder", "dev", "designer", "marketing"], sourceStages: ["PRODUCT_SPEC", "AUDIT"], templatePath: "02-product/09-product-roadmap.md.hbs", placeholders: ["COMPANY_NAME", "ROADMAP", "CURRENT_DATE"] },
  { id: "release-plan", category: "02-product", slot: "10", title: "Release Plan", description: "What ships in each version.", tier: "C", roles: ["dev", "support"], sourceStages: ["AUDIT", "BUILD"], templatePath: "02-product/10-release-plan.md.hbs", placeholders: ["COMPANY_NAME", "RELEASES", "CURRENT_DATE"] },
  { id: "changelog-template", category: "02-product", slot: "11", title: "Changelog Template", description: "Public and internal record of product changes.", tier: "D", roles: ["dev", "support", "marketing"], sourceStages: [], templatePath: "02-product/11-changelog-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "product-decision-log", category: "02-product", slot: "12", title: "Product Decision Log", description: "Why major product decisions were made.", tier: "D", roles: ["founder", "dev"], sourceStages: [], templatePath: "02-product/12-product-decision-log.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "product-analytics-plan", category: "02-product", slot: "13", title: "Product Analytics Plan", description: "Events to track: signups, activation, retention, churn, conversions.", tier: "C", roles: ["dev", "marketing", "founder"], sourceStages: ["PRODUCT_SPEC"], templatePath: "02-product/13-product-analytics-plan.md.hbs", placeholders: ["COMPANY_NAME", "EVENTS", "CURRENT_DATE"] },
  { id: "beta-testing-plan", category: "02-product", slot: "14", title: "Beta Testing Plan", description: "Who tests, what they test, feedback method, pass/fail criteria.", tier: "D", roles: ["dev", "founder", "support"], sourceStages: [], templatePath: "02-product/14-beta-testing-plan.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "feedback-management", category: "02-product", slot: "15", title: "Feedback Management Process", description: "How customer feedback becomes product work.", tier: "D", roles: ["dev", "support", "founder"], sourceStages: [], templatePath: "02-product/15-feedback-management.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 03-design-brand --------
  { id: "brand-strategy", category: "03-design-brand", slot: "00", title: "Brand Strategy", description: "Brand personality, positioning, audience, promise.", tier: "B", roles: ["founder", "designer", "marketing"], sourceStages: ["BRAND"], templatePath: "03-design-brand/00-brand-strategy.md.hbs", placeholders: ["COMPANY_NAME", "PERSONALITY", "POSITIONING", "PROMISE", "CURRENT_DATE"] },
  { id: "brand-guide", category: "03-design-brand", slot: "01", title: "Brand Guide", description: "Colours, fonts, tone, imagery, layout rules.", tier: "A", roles: ["designer", "marketing", "dev"], sourceStages: ["BRAND"], templatePath: "03-design-brand/01-brand-guide.md.hbs", placeholders: ["COMPANY_NAME", "PRIMARY_HEX", "SECONDARY_HEX", "HEADING_FONT", "BODY_FONT", "TONE", "CURRENT_DATE"] },
  { id: "logo-pack", category: "03-design-brand", slot: "02", title: "Logo Pack", description: "Logo files, usage rules, spacing, light/dark variants.", tier: "B", roles: ["designer", "marketing", "dev"], sourceStages: ["BRAND"], templatePath: "03-design-brand/02-logo-pack.md.hbs", placeholders: ["COMPANY_NAME", "LOGO_PRIMARY", "LOGO_VARIANTS", "CURRENT_DATE"] },
  { id: "design-system", category: "03-design-brand", slot: "03", title: "Design System", description: "Buttons, inputs, cards, modals, navigation, spacing, tokens.", tier: "A", roles: ["designer", "dev"], sourceStages: ["BRAND", "HANDOFF"], templatePath: "03-design-brand/03-design-system.md.hbs", placeholders: ["COMPANY_NAME", "TOKENS", "COMPONENTS", "SLIDERS", "CURRENT_DATE"] },
  { id: "wireframe-pack", category: "03-design-brand", slot: "04", title: "Wireframe Pack", description: "Low-fidelity layouts for every screen.", tier: "A", roles: ["designer", "dev"], sourceStages: ["WIREFRAME"], templatePath: "03-design-brand/04-wireframe-pack.md.hbs", placeholders: ["COMPANY_NAME", "SCREENS", "CURRENT_DATE"] },
  { id: "design-handoff", category: "03-design-brand", slot: "05", title: "Design Handoff Document", description: "Specs for developers: spacing, states, breakpoints.", tier: "B", roles: ["dev", "designer"], sourceStages: ["HANDOFF"], templatePath: "03-design-brand/05-design-handoff.md.hbs", placeholders: ["COMPANY_NAME", "SLIDERS", "TOKENS", "HTML_HASH", "CURRENT_DATE"] },
  { id: "ui-component-library", category: "03-design-brand", slot: "06", title: "UI Component Library", description: "Reusable interface components.", tier: "C", roles: ["dev", "designer"], sourceStages: ["BUILD", "HANDOFF"], templatePath: "03-design-brand/06-ui-component-library.md.hbs", placeholders: ["COMPANY_NAME", "COMPONENTS", "CURRENT_DATE"] },
  { id: "ux-research-notes", category: "03-design-brand", slot: "07", title: "UX Research Notes", description: "User interviews, problems, needs, behaviour.", tier: "C", roles: ["designer", "founder"], sourceStages: ["VALIDATION"], templatePath: "03-design-brand/07-ux-research-notes.md.hbs", placeholders: ["COMPANY_NAME", "INTERVIEWS", "INSIGHTS", "CURRENT_DATE"] },
  { id: "high-fidelity-mockups", category: "03-design-brand", slot: "08", title: "High-Fidelity Mockups", description: "Final visual UI designs.", tier: "D", roles: ["designer", "dev", "marketing"], sourceStages: [], templatePath: "03-design-brand/08-high-fidelity-mockups.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "information-architecture", category: "03-design-brand", slot: "09", title: "Information Architecture", description: "Navigation, pages, sections, hierarchy.", tier: "C", roles: ["designer", "dev"], sourceStages: ["WIREFRAME"], templatePath: "03-design-brand/09-information-architecture.md.hbs", placeholders: ["COMPANY_NAME", "IA_TREE", "CURRENT_DATE"] },
  { id: "accessibility-checklist", category: "03-design-brand", slot: "10", title: "Accessibility Checklist", description: "Contrast, keyboard, screen-reader, WCAG essentials.", tier: "D", roles: ["designer", "dev"], sourceStages: [], templatePath: "03-design-brand/10-accessibility-checklist.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "empty-error-loading", category: "03-design-brand", slot: "11", title: "Empty / Error / Loading State Guide", description: "What users see when things go wrong or data is missing.", tier: "D", roles: ["designer", "dev"], sourceStages: [], templatePath: "03-design-brand/11-empty-error-loading.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "copy-microcopy-guide", category: "03-design-brand", slot: "12", title: "Copy and Microcopy Guide", description: "Button text, labels, validation, onboarding copy.", tier: "D", roles: ["designer", "marketing", "dev"], sourceStages: [], templatePath: "03-design-brand/12-copy-microcopy-guide.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "marketing-design-assets", category: "03-design-brand", slot: "13", title: "Marketing Design Assets", description: "Social banners, launch images, ad graphics, pitch visuals.", tier: "D", roles: ["designer", "marketing"], sourceStages: [], templatePath: "03-design-brand/13-marketing-design-assets.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 04-engineering --------
  { id: "developer-brief", category: "04-engineering", slot: "00", title: "Developer Brief", description: "Product overview, business goals, technical expectations, constraints.", tier: "A", roles: ["dev", "contractor"], sourceStages: ["PRODUCT_SPEC", "HANDOFF", "BACKEND"], templatePath: "04-engineering/00-developer-brief.md.hbs", placeholders: ["COMPANY_NAME", "PRODUCT_NAME", "STACK", "CONSTRAINTS", "CURRENT_DATE"] },
  { id: "technical-specification", category: "04-engineering", slot: "01", title: "Technical Specification", description: "Architecture, stack, services, database, APIs, integrations.", tier: "A", roles: ["dev"], sourceStages: ["HANDOFF", "BACKEND", "BUILD"], templatePath: "04-engineering/01-technical-specification.md.hbs", placeholders: ["COMPANY_NAME", "ARCHITECTURE", "STACK", "CURRENT_DATE"] },
  { id: "architecture-diagram", category: "04-engineering", slot: "02", title: "Architecture Diagram", description: "Frontend, backend, database, services, third-party tools.", tier: "B", roles: ["dev"], sourceStages: ["BUILD", "BACKEND"], templatePath: "04-engineering/02-architecture-diagram.md.hbs", placeholders: ["COMPANY_NAME", "DIAGRAM_MERMAID", "CURRENT_DATE"] },
  { id: "database-schema", category: "04-engineering", slot: "03", title: "Database Schema", description: "Tables / collections, fields, relationships, indexes.", tier: "A", roles: ["dev"], sourceStages: ["BACKEND"], templatePath: "04-engineering/03-database-schema.md.hbs", placeholders: ["COMPANY_NAME", "COLLECTIONS", "CURRENT_DATE"] },
  { id: "api-specification", category: "04-engineering", slot: "04", title: "API Specification", description: "REST/GraphQL endpoints, request/response contracts, auth.", tier: "A", roles: ["dev"], sourceStages: ["BACKEND"], templatePath: "04-engineering/04-api-specification.md.hbs", placeholders: ["COMPANY_NAME", "ENDPOINTS", "AUTH", "CURRENT_DATE"] },
  { id: "integration-specification", category: "04-engineering", slot: "05", title: "Integration Specification", description: "Stripe, email, auth, CRM, analytics, AI APIs, storage.", tier: "C", roles: ["dev"], sourceStages: ["BUILD", "CRM"], templatePath: "04-engineering/05-integration-specification.md.hbs", placeholders: ["COMPANY_NAME", "INTEGRATIONS", "CURRENT_DATE"] },
  { id: "environment-setup-guide", category: "04-engineering", slot: "06", title: "Environment Setup Guide", description: "How to install and run the project locally.", tier: "B", roles: ["dev", "contractor"], sourceStages: ["BUILD"], templatePath: "04-engineering/06-environment-setup-guide.md.hbs", placeholders: ["COMPANY_NAME", "REPO_URL", "STEPS", "CURRENT_DATE"] },
  { id: "repository-structure", category: "04-engineering", slot: "07", title: "Repository Structure Guide", description: "Folders, packages, modules, naming.", tier: "C", roles: ["dev", "contractor"], sourceStages: ["BUILD"], templatePath: "04-engineering/07-repository-structure.md.hbs", placeholders: ["COMPANY_NAME", "STRUCTURE", "CURRENT_DATE"] },
  { id: "coding-standards", category: "04-engineering", slot: "08", title: "Coding Standards", description: "Formatting, naming, linting, comments, patterns.", tier: "D", roles: ["dev", "contractor"], sourceStages: [], templatePath: "04-engineering/08-coding-standards.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "git-workflow", category: "04-engineering", slot: "09", title: "Branching and Git Workflow", description: "Branch names, PR rules, merge process, release branches.", tier: "D", roles: ["dev", "contractor"], sourceStages: [], templatePath: "04-engineering/09-git-workflow.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "pull-request-template", category: "04-engineering", slot: "10", title: "Pull Request Template", description: "Checklist before code is merged.", tier: "D", roles: ["dev", "contractor"], sourceStages: [], templatePath: "04-engineering/10-pull-request-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "testing-strategy", category: "04-engineering", slot: "11", title: "Testing Strategy", description: "Unit, integration, E2E, security, performance testing.", tier: "A", roles: ["dev"], sourceStages: ["AUDIT"], templatePath: "04-engineering/11-testing-strategy.md.hbs", placeholders: ["COMPANY_NAME", "TEST_TYPES", "COVERAGE_TARGETS", "CURRENT_DATE"] },
  { id: "test-plan", category: "04-engineering", slot: "12", title: "Test Plan", description: "What must be tested before release.", tier: "C", roles: ["dev"], sourceStages: ["AUDIT"], templatePath: "04-engineering/12-test-plan.md.hbs", placeholders: ["COMPANY_NAME", "TEST_PLAN", "CURRENT_DATE"] },
  { id: "deployment-guide", category: "04-engineering", slot: "13", title: "Deployment Guide", description: "How code goes from local to staging to production.", tier: "A", roles: ["dev"], sourceStages: ["BUILD", "BACKEND"], templatePath: "04-engineering/13-deployment-guide.md.hbs", placeholders: ["COMPANY_NAME", "STAGES", "CURRENT_DATE"] },
  { id: "devops-runbook", category: "04-engineering", slot: "14", title: "DevOps Runbook", description: "CI/CD, hosting, logs, monitoring, rollback.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "04-engineering/14-devops-runbook.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "error-handling-standard", category: "04-engineering", slot: "15", title: "Error Handling Standard", description: "API errors, frontend errors, logging, user-facing messages.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "04-engineering/15-error-handling-standard.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "observability-plan", category: "04-engineering", slot: "16", title: "Observability Plan", description: "Logs, metrics, alerts, uptime, tracing.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "04-engineering/16-observability-plan.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "backup-recovery-plan", category: "04-engineering", slot: "17", title: "Backup and Recovery Plan", description: "Database backups, restore process, disaster recovery.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "04-engineering/17-backup-recovery-plan.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "performance-requirements", category: "04-engineering", slot: "18", title: "Performance Requirements", description: "Load times, API response targets, scaling assumptions.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "04-engineering/18-performance-requirements.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "technical-debt-register", category: "04-engineering", slot: "19", title: "Technical Debt Register", description: "Known shortcuts and future fixes.", tier: "C", roles: ["dev", "founder"], sourceStages: ["AUDIT"], templatePath: "04-engineering/19-technical-debt-register.md.hbs", placeholders: ["COMPANY_NAME", "DEBT_ITEMS", "CURRENT_DATE"] },
  { id: "ai-dev-policy", category: "04-engineering", slot: "20", title: "AI Usage Policy for Developers", description: "What developers can use AI for; what cannot be pasted into AI tools.", tier: "D", roles: ["dev", "contractor"], sourceStages: [], templatePath: "04-engineering/20-ai-dev-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "ai-product-policy", category: "04-engineering", slot: "21", title: "AI Product Policy", description: "What the AI feature does and does not do.", tier: "D", roles: ["dev", "support", "marketing"], sourceStages: [], templatePath: "04-engineering/21-ai-product-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "prompt-library", category: "04-engineering", slot: "22", title: "Prompt Library", description: "Approved prompts, system prompts, reusable chains.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "04-engineering/22-prompt-library.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "ai-safety-abuse-policy", category: "04-engineering", slot: "23", title: "AI Safety and Abuse Policy", description: "Misuse cases, refusal logic, risk controls.", tier: "D", roles: ["dev", "support", "founder"], sourceStages: [], templatePath: "04-engineering/23-ai-safety-abuse-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "ai-evaluation-plan", category: "04-engineering", slot: "24", title: "AI Evaluation Plan", description: "Accuracy tests, hallucination tests, regression tests.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "04-engineering/24-ai-evaluation-plan.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 05-security-data-compliance --------
  { id: "privacy-policy", category: "05-security-data-compliance", slot: "00", title: "Privacy Policy", description: "What data is collected, why, retention, user rights.", tier: "C", roles: ["founder", "dev", "marketing", "support", "contractor"], sourceStages: ["UK_SETUP", "BACKEND"], templatePath: "05-security-data-compliance/00-privacy-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_REGISTERED_OFFICE", "DPO_EMAIL", "DATA_CATEGORIES", "RETENTION_PERIOD", "CURRENT_DATE"] },
  { id: "terms-of-service", category: "05-security-data-compliance", slot: "01", title: "Terms of Service", description: "Rules for using the SaaS product.", tier: "C", roles: ["founder", "support"], sourceStages: ["UK_SETUP"], templatePath: "05-security-data-compliance/01-terms-of-service.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_NUMBER", "JURISDICTION", "CURRENT_DATE"] },
  { id: "cookie-policy", category: "05-security-data-compliance", slot: "02", title: "Cookie Policy", description: "Cookies, analytics, tracking, consent.", tier: "D", roles: ["founder", "dev", "marketing"], sourceStages: [], templatePath: "05-security-data-compliance/02-cookie-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "data-processing-agreement", category: "05-security-data-compliance", slot: "03", title: "Data Processing Agreement", description: "Required for B2B customers where personal data is processed.", tier: "D", roles: ["founder", "sales"], sourceStages: [], templatePath: "05-security-data-compliance/03-data-processing-agreement.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "ropa", category: "05-security-data-compliance", slot: "04", title: "Record of Processing Activities", description: "What personal data is processed, purpose, sharing, retention.", tier: "C", roles: ["founder", "dev"], sourceStages: ["UK_SETUP", "BACKEND"], templatePath: "05-security-data-compliance/04-ropa.md.hbs", placeholders: ["COMPANY_NAME", "ACTIVITIES", "CURRENT_DATE"] },
  { id: "data-retention-policy", category: "05-security-data-compliance", slot: "05", title: "Data Retention Policy", description: "How long data is kept and when it is deleted.", tier: "D", roles: ["founder", "dev", "support"], sourceStages: [], templatePath: "05-security-data-compliance/05-data-retention-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "data-deletion-procedure", category: "05-security-data-compliance", slot: "06", title: "Data Deletion Procedure", description: "How to delete user / customer data on request.", tier: "D", roles: ["dev", "support"], sourceStages: [], templatePath: "05-security-data-compliance/06-data-deletion-procedure.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "dsar-procedure", category: "05-security-data-compliance", slot: "07", title: "Data Subject Access Request", description: "How to respond when users ask for their data.", tier: "D", roles: ["support", "founder"], sourceStages: [], templatePath: "05-security-data-compliance/07-dsar-procedure.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "lawful-basis-assessment", category: "05-security-data-compliance", slot: "08", title: "Lawful Basis Assessment", description: "Why the company is allowed to process each data type.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "05-security-data-compliance/08-lawful-basis-assessment.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "lia", category: "05-security-data-compliance", slot: "09", title: "Legitimate Interests Assessment", description: "Used when relying on legitimate interests.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "05-security-data-compliance/09-lia.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "dpia", category: "05-security-data-compliance", slot: "10", title: "Data Protection Impact Assessment", description: "Risk assessment for high-risk data processing.", tier: "D", roles: ["founder", "dev"], sourceStages: [], templatePath: "05-security-data-compliance/10-dpia.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "subprocessor-list", category: "05-security-data-compliance", slot: "11", title: "Subprocessor List", description: "Third-party tools that process customer data.", tier: "C", roles: ["founder", "sales", "dev"], sourceStages: ["BUILD", "BACKEND", "CRM"], templatePath: "05-security-data-compliance/11-subprocessor-list.md.hbs", placeholders: ["COMPANY_NAME", "SUBPROCESSORS", "CURRENT_DATE"] },
  { id: "international-transfer", category: "05-security-data-compliance", slot: "12", title: "International Transfer Assessment", description: "Required if data is sent outside the UK/EU.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "05-security-data-compliance/12-international-transfer.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "breach-response-plan", category: "05-security-data-compliance", slot: "13", title: "Breach Response Plan", description: "What to do if data is leaked or accessed unlawfully.", tier: "D", roles: ["founder", "dev", "support"], sourceStages: [], templatePath: "05-security-data-compliance/13-breach-response-plan.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "information-security-policy", category: "05-security-data-compliance", slot: "14", title: "Information Security Policy", description: "Overall security rules.", tier: "D", roles: ["founder", "dev", "contractor"], sourceStages: [], templatePath: "05-security-data-compliance/14-information-security-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "password-auth-policy", category: "05-security-data-compliance", slot: "15", title: "Password and Authentication Policy", description: "Password managers, MFA, admin accounts.", tier: "D", roles: ["dev", "support", "founder", "contractor"], sourceStages: [], templatePath: "05-security-data-compliance/15-password-auth-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "access-control-policy", category: "05-security-data-compliance", slot: "16", title: "Access Control Policy", description: "Who can access what data and systems.", tier: "D", roles: ["dev", "founder", "contractor"], sourceStages: [], templatePath: "05-security-data-compliance/16-access-control-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "access-management-procedure", category: "05-security-data-compliance", slot: "17", title: "Access Management Procedure", description: "Joining, moving role, leaving company.", tier: "D", roles: ["founder", "dev"], sourceStages: [], templatePath: "05-security-data-compliance/17-access-management-procedure.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "device-security-policy", category: "05-security-data-compliance", slot: "18", title: "Device Security Policy", description: "Laptops, updates, encryption, antivirus, lost devices.", tier: "D", roles: ["dev", "contractor", "founder"], sourceStages: [], templatePath: "05-security-data-compliance/18-device-security-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "secure-development-policy", category: "05-security-data-compliance", slot: "19", title: "Secure Development Policy", description: "Secure coding, secrets, dependency checks, reviews.", tier: "D", roles: ["dev", "contractor"], sourceStages: [], templatePath: "05-security-data-compliance/19-secure-development-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "vulnerability-management", category: "05-security-data-compliance", slot: "20", title: "Vulnerability Management Plan", description: "How vulnerabilities are found, triaged, fixed.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "05-security-data-compliance/20-vulnerability-management.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "incident-response-plan", category: "05-security-data-compliance", slot: "21", title: "Incident Response Plan", description: "What to do during a hack, breach, outage, account compromise.", tier: "D", roles: ["founder", "dev", "support"], sourceStages: [], templatePath: "05-security-data-compliance/21-incident-response-plan.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "security-risk-register", category: "05-security-data-compliance", slot: "22", title: "Security Risk Register", description: "Known security risks and mitigations.", tier: "D", roles: ["dev", "founder"], sourceStages: [], templatePath: "05-security-data-compliance/22-security-risk-register.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "vendor-security-review", category: "05-security-data-compliance", slot: "23", title: "Third-Party Vendor Security Review", description: "How to assess tools like Stripe, Supabase, OpenAI.", tier: "D", roles: ["dev", "founder"], sourceStages: [], templatePath: "05-security-data-compliance/23-vendor-security-review.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "secrets-management-policy", category: "05-security-data-compliance", slot: "24", title: "Secrets Management Policy", description: "API keys, tokens, environment variables.", tier: "D", roles: ["dev", "contractor"], sourceStages: [], templatePath: "05-security-data-compliance/24-secrets-management-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "admin-panel-access-policy", category: "05-security-data-compliance", slot: "25", title: "Admin Panel Access Policy", description: "Who can access internal admin tools.", tier: "D", roles: ["dev", "support", "founder"], sourceStages: [], templatePath: "05-security-data-compliance/25-admin-panel-access-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "ai-security-policy", category: "05-security-data-compliance", slot: "26", title: "AI Tool Security Policy", description: "What company / customer data can be used with AI tools.", tier: "D", roles: ["dev", "contractor", "support"], sourceStages: [], templatePath: "05-security-data-compliance/26-ai-security-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "customer-data-handling-sop", category: "05-security-data-compliance", slot: "27", title: "Customer Data Handling SOP", description: "Rules for support / admin staff viewing customer data.", tier: "D", roles: ["support", "dev", "founder"], sourceStages: [], templatePath: "05-security-data-compliance/27-customer-data-handling-sop.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 06-people-hr --------
  { id: "employment-contract", category: "06-people-hr", slot: "00", title: "Employment Contract Template", description: "Role, pay, hours, duties, notice, confidentiality.", tier: "C", roles: ["founder"], sourceStages: ["UK_SETUP"], templatePath: "06-people-hr/00-employment-contract.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_REGISTERED_OFFICE", "ROLE", "SALARY", "CURRENT_DATE"] },
  { id: "written-particulars", category: "06-people-hr", slot: "01", title: "Written Statement of Employment Particulars", description: "Statutory UK employment particulars.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/01-written-particulars.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "contractor-agreement", category: "06-people-hr", slot: "02", title: "Contractor Agreement Template", description: "Terms for freelancers and contractors.", tier: "C", roles: ["founder", "contractor"], sourceStages: ["UK_SETUP"], templatePath: "06-people-hr/02-contractor-agreement.md.hbs", placeholders: ["COMPANY_NAME", "CONTRACTOR_NAME", "SCOPE", "FEE", "CURRENT_DATE"] },
  { id: "nda", category: "06-people-hr", slot: "03", title: "NDA / Confidentiality Agreement", description: "Protects private company / product information.", tier: "D", roles: ["founder", "contractor"], sourceStages: [], templatePath: "06-people-hr/03-nda.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "employee-handbook", category: "06-people-hr", slot: "04", title: "Employee Handbook", description: "Company rules and expectations.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/04-employee-handbook.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "code-of-conduct", category: "06-people-hr", slot: "05", title: "Code of Conduct", description: "Behaviour standards.", tier: "D", roles: ["founder", "contractor"], sourceStages: [], templatePath: "06-people-hr/05-code-of-conduct.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "remote-work-policy", category: "06-people-hr", slot: "06", title: "Remote Work Policy", description: "Working hours, communication, equipment, security.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/06-remote-work-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "holiday-policy", category: "06-people-hr", slot: "07", title: "Holiday Policy", description: "Leave entitlement and booking process.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/07-holiday-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "sickness-policy", category: "06-people-hr", slot: "08", title: "Sickness Policy", description: "Reporting absence, sick pay, process.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/08-sickness-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "expense-policy", category: "06-people-hr", slot: "09", title: "Expense Policy", description: "What can be claimed and how.", tier: "D", roles: ["founder", "finance"], sourceStages: [], templatePath: "06-people-hr/09-expense-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "disciplinary-policy", category: "06-people-hr", slot: "10", title: "Disciplinary Policy", description: "How misconduct is handled.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/10-disciplinary-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "grievance-policy", category: "06-people-hr", slot: "11", title: "Grievance Policy", description: "How employees raise problems.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/11-grievance-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "equal-opportunities", category: "06-people-hr", slot: "12", title: "Equal Opportunities Policy", description: "Anti-discrimination and fair treatment.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/12-equal-opportunities.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "recruitment-process", category: "06-people-hr", slot: "13", title: "Recruitment Process", description: "Hiring steps, interview structure, scoring.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/13-recruitment-process.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "onboarding-checklist", category: "06-people-hr", slot: "14", title: "Onboarding Checklist", description: "Accounts, equipment, training, documents to read.", tier: "C", roles: ["founder", "dev", "contractor"], sourceStages: [], templatePath: "06-people-hr/14-onboarding-checklist.md.hbs", placeholders: ["COMPANY_NAME", "ROLE", "TOOLS", "DAY_ONE_TASKS", "CURRENT_DATE"] },
  { id: "offboarding-checklist", category: "06-people-hr", slot: "15", title: "Offboarding Checklist", description: "Remove access, recover equipment, final pay, exit interview.", tier: "C", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/15-offboarding-checklist.md.hbs", placeholders: ["COMPANY_NAME", "ROLE", "ACCESS_TO_REVOKE", "CURRENT_DATE"] },
  { id: "training-matrix", category: "06-people-hr", slot: "16", title: "Training Matrix", description: "Who needs what training.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/16-training-matrix.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "org-chart", category: "06-people-hr", slot: "17", title: "Org Chart", description: "Reporting lines and responsibilities.", tier: "C", roles: ["founder", "contractor"], sourceStages: [], templatePath: "06-people-hr/17-org-chart.md.hbs", placeholders: ["COMPANY_NAME", "STRUCTURE", "CURRENT_DATE"] },
  { id: "role-descriptions", category: "06-people-hr", slot: "18", title: "Role Descriptions", description: "What each role does and who owns each function.", tier: "C", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/18-role-descriptions.md.hbs", placeholders: ["COMPANY_NAME", "ROLES", "CURRENT_DATE"] },
  { id: "role-scorecards", category: "06-people-hr", slot: "19", title: "Role Scorecards", description: "What success looks like for each role.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "06-people-hr/19-role-scorecards.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "communication-policy", category: "06-people-hr", slot: "20", title: "Communication Policy", description: "Slack/Teams/email rules, response times, escalation.", tier: "D", roles: ["founder", "dev", "support", "contractor"], sourceStages: [], templatePath: "06-people-hr/20-communication-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 07-finance-admin --------
  { id: "financial-model", category: "07-finance-admin", slot: "00", title: "Financial Model", description: "Revenue, costs, runway, P&L, hiring plan.", tier: "A", roles: ["founder", "finance"], sourceStages: ["FINANCE", "VALIDATION"], templatePath: "07-finance-admin/00-financial-model.md.hbs", placeholders: ["COMPANY_NAME", "REVENUE", "COSTS", "RUNWAY", "HIRES", "CURRENT_DATE"] },
  { id: "startup-budget", category: "07-finance-admin", slot: "01", title: "Startup Budget", description: "Initial setup costs, software, contractors, legal, marketing.", tier: "B", roles: ["founder", "finance"], sourceStages: ["FINANCE"], templatePath: "07-finance-admin/01-startup-budget.md.hbs", placeholders: ["COMPANY_NAME", "CATEGORIES", "CURRENT_DATE"] },
  { id: "cashflow-forecast", category: "07-finance-admin", slot: "02", title: "Cash Flow Forecast", description: "Money in and out by month.", tier: "B", roles: ["founder", "finance"], sourceStages: ["FINANCE"], templatePath: "07-finance-admin/02-cashflow-forecast.md.hbs", placeholders: ["COMPANY_NAME", "MONTHS", "CURRENT_DATE"] },
  { id: "chart-of-accounts", category: "07-finance-admin", slot: "03", title: "Chart of Accounts", description: "Accounting categories.", tier: "D", roles: ["finance"], sourceStages: [], templatePath: "07-finance-admin/03-chart-of-accounts.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "invoice-template", category: "07-finance-admin", slot: "04", title: "Invoice Template", description: "Standard invoice format.", tier: "D", roles: ["finance", "founder"], sourceStages: [], templatePath: "07-finance-admin/04-invoice-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "purchase-order-process", category: "07-finance-admin", slot: "05", title: "Purchase Order Process", description: "How spending is approved.", tier: "D", roles: ["finance", "founder"], sourceStages: [], templatePath: "07-finance-admin/05-purchase-order-process.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "expense-claim-form", category: "07-finance-admin", slot: "06", title: "Expense Claim Form", description: "Employee / contractor expense claims.", tier: "D", roles: ["finance", "founder", "contractor"], sourceStages: [], templatePath: "07-finance-admin/06-expense-claim-form.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "payroll-process", category: "07-finance-admin", slot: "07", title: "Payroll Process", description: "Salaries, tax, pensions, payroll dates.", tier: "D", roles: ["finance", "founder"], sourceStages: [], templatePath: "07-finance-admin/07-payroll-process.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "tax-calendar", category: "07-finance-admin", slot: "08", title: "Tax Calendar", description: "VAT, corporation tax, payroll deadlines.", tier: "D", roles: ["finance", "founder"], sourceStages: [], templatePath: "07-finance-admin/08-tax-calendar.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "subscription-cost-register", category: "07-finance-admin", slot: "09", title: "Subscription Cost Register", description: "SaaS tools, renewals, owners.", tier: "C", roles: ["finance", "founder", "dev"], sourceStages: ["FINANCE", "BACKEND"], templatePath: "07-finance-admin/09-subscription-cost-register.md.hbs", placeholders: ["COMPANY_NAME", "SUBSCRIPTIONS", "CURRENT_DATE"] },
  { id: "revenue-recognition", category: "07-finance-admin", slot: "10", title: "Revenue Recognition Policy", description: "How subscription revenue is recorded.", tier: "D", roles: ["finance"], sourceStages: [], templatePath: "07-finance-admin/10-revenue-recognition.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "pricing-discount-approval", category: "07-finance-admin", slot: "11", title: "Pricing and Discount Approval", description: "Who can discount and by how much.", tier: "D", roles: ["finance", "sales", "founder"], sourceStages: [], templatePath: "07-finance-admin/11-pricing-discount-approval.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "payment-failure-process", category: "07-finance-admin", slot: "12", title: "Payment Failure Process", description: "What happens when customer payments fail.", tier: "D", roles: ["finance", "support", "dev"], sourceStages: [], templatePath: "07-finance-admin/12-payment-failure-process.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "debt-collection-process", category: "07-finance-admin", slot: "13", title: "Debt Collection Process", description: "How overdue invoices are handled.", tier: "D", roles: ["finance", "founder"], sourceStages: [], templatePath: "07-finance-admin/13-debt-collection-process.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "investor-reporting", category: "07-finance-admin", slot: "14", title: "Investor Reporting Template", description: "Monthly / quarterly business updates.", tier: "D", roles: ["founder", "finance"], sourceStages: [], templatePath: "07-finance-admin/14-investor-reporting.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "procurement-policy", category: "07-finance-admin", slot: "15", title: "Procurement Policy", description: "How the company buys tools / services.", tier: "D", roles: ["finance", "founder"], sourceStages: [], templatePath: "07-finance-admin/15-procurement-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "vendor-register", category: "07-finance-admin", slot: "16", title: "Vendor Register", description: "Suppliers, contracts, risks, contacts.", tier: "D", roles: ["finance", "founder"], sourceStages: [], templatePath: "07-finance-admin/16-vendor-register.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 08-sales-marketing --------
  { id: "go-to-market-plan", category: "08-sales-marketing", slot: "00", title: "Go-To-Market Plan", description: "Launch audience, messaging, offers, timeline.", tier: "B", roles: ["founder", "marketing", "sales"], sourceStages: ["LAUNCH", "CRM", "BRAND"], templatePath: "08-sales-marketing/00-go-to-market-plan.md.hbs", placeholders: ["COMPANY_NAME", "AUDIENCE", "CHANNELS", "TIMELINE", "CURRENT_DATE"] },
  { id: "sales-playbook", category: "08-sales-marketing", slot: "01", title: "Sales Playbook", description: "Full sales process from lead to close.", tier: "B", roles: ["sales", "founder"], sourceStages: ["CRM"], templatePath: "08-sales-marketing/01-sales-playbook.md.hbs", placeholders: ["COMPANY_NAME", "STAGES", "SCRIPTS", "CURRENT_DATE"] },
  { id: "buyer-personas", category: "08-sales-marketing", slot: "02", title: "Buyer Personas", description: "Decision maker, user, influencer, blocker.", tier: "B", roles: ["sales", "marketing", "founder"], sourceStages: ["VALIDATION", "CRM"], templatePath: "08-sales-marketing/02-buyer-personas.md.hbs", placeholders: ["COMPANY_NAME", "PERSONAS", "CURRENT_DATE"] },
  { id: "crm-process", category: "08-sales-marketing", slot: "03", title: "CRM Process", description: "Pipeline stages, fields, data hygiene.", tier: "B", roles: ["sales", "founder"], sourceStages: ["CRM"], templatePath: "08-sales-marketing/03-crm-process.md.hbs", placeholders: ["COMPANY_NAME", "STAGES", "FIELDS", "CURRENT_DATE"] },
  { id: "website-copy", category: "08-sales-marketing", slot: "04", title: "Website Copy", description: "Homepage, features, pricing, FAQ, about.", tier: "B", roles: ["marketing", "designer", "founder"], sourceStages: ["LAUNCH", "BRAND"], templatePath: "08-sales-marketing/04-website-copy.md.hbs", placeholders: ["COMPANY_NAME", "HOMEPAGE", "FEATURES", "PRICING", "FAQ", "ABOUT", "CURRENT_DATE"] },
  { id: "launch-plan", category: "08-sales-marketing", slot: "05", title: "Launch Plan", description: "Product Hunt, email list, ads, founder posts, beta users.", tier: "B", roles: ["founder", "marketing"], sourceStages: ["LAUNCH", "CRM"], templatePath: "08-sales-marketing/05-launch-plan.md.hbs", placeholders: ["COMPANY_NAME", "CHANNELS", "DATES", "CURRENT_DATE"] },
  { id: "pitch-deck", category: "08-sales-marketing", slot: "06", title: "Pitch Deck", description: "Investor-grade slide deck rendered from media stage.", tier: "C", roles: ["founder"], sourceStages: ["MEDIA", "BRAND", "FINANCE"], templatePath: "08-sales-marketing/06-pitch-deck.md.hbs", placeholders: ["COMPANY_NAME", "SLIDES", "CURRENT_DATE"] },
  { id: "brand-messaging-guide", category: "08-sales-marketing", slot: "07", title: "Brand Messaging Guide", description: "Tagline, elevator pitch, product descriptions.", tier: "C", roles: ["marketing", "founder"], sourceStages: ["BRAND"], templatePath: "08-sales-marketing/07-brand-messaging-guide.md.hbs", placeholders: ["COMPANY_NAME", "TAGLINE", "ELEVATOR", "CURRENT_DATE"] },
  { id: "seo-strategy", category: "08-sales-marketing", slot: "08", title: "SEO Strategy", description: "Keywords, pages, content clusters.", tier: "D", roles: ["marketing"], sourceStages: [], templatePath: "08-sales-marketing/08-seo-strategy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "content-calendar", category: "08-sales-marketing", slot: "09", title: "Content Calendar", description: "Blogs, videos, newsletters, social posts.", tier: "D", roles: ["marketing"], sourceStages: [], templatePath: "08-sales-marketing/09-content-calendar.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "social-media-strategy", category: "08-sales-marketing", slot: "10", title: "Social Media Strategy", description: "Platforms, tone, posting cadence.", tier: "D", roles: ["marketing"], sourceStages: [], templatePath: "08-sales-marketing/10-social-media-strategy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "press-kit", category: "08-sales-marketing", slot: "11", title: "PR / Press Kit", description: "Company bio, founder bio, logo, screenshots, press release.", tier: "D", roles: ["marketing", "founder"], sourceStages: [], templatePath: "08-sales-marketing/11-press-kit.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "case-study-template", category: "08-sales-marketing", slot: "12", title: "Case Study Template", description: "Customer problem, solution, results.", tier: "D", roles: ["marketing", "sales"], sourceStages: [], templatePath: "08-sales-marketing/12-case-study-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "email-marketing-flows", category: "08-sales-marketing", slot: "13", title: "Email Marketing Flows", description: "Welcome, onboarding, activation, upgrade, churn prevention.", tier: "D", roles: ["marketing", "support"], sourceStages: [], templatePath: "08-sales-marketing/13-email-marketing-flows.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "ad-campaign-briefs", category: "08-sales-marketing", slot: "14", title: "Ad Campaign Briefs", description: "Audience, creative, budget, conversion goal.", tier: "D", roles: ["marketing"], sourceStages: [], templatePath: "08-sales-marketing/14-ad-campaign-briefs.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "affiliate-referral-plan", category: "08-sales-marketing", slot: "15", title: "Affiliate / Referral Plan", description: "Rewards, tracking, rules.", tier: "D", roles: ["marketing", "sales"], sourceStages: [], templatePath: "08-sales-marketing/15-affiliate-referral-plan.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "analytics-dashboard-spec", category: "08-sales-marketing", slot: "16", title: "Analytics Dashboard Spec", description: "Traffic, conversion, CAC, activation, retention.", tier: "D", roles: ["marketing", "dev", "founder"], sourceStages: [], templatePath: "08-sales-marketing/16-analytics-dashboard-spec.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "discovery-call-script", category: "08-sales-marketing", slot: "17", title: "Discovery Call Script", description: "Questions to understand customer pain.", tier: "D", roles: ["sales"], sourceStages: [], templatePath: "08-sales-marketing/17-discovery-call-script.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "demo-script", category: "08-sales-marketing", slot: "18", title: "Demo Script", description: "How to present the product.", tier: "D", roles: ["sales"], sourceStages: [], templatePath: "08-sales-marketing/18-demo-script.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "objection-handling", category: "08-sales-marketing", slot: "19", title: "Objection Handling Guide", description: "Common objections and responses.", tier: "D", roles: ["sales"], sourceStages: [], templatePath: "08-sales-marketing/19-objection-handling.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "pricing-sheet", category: "08-sales-marketing", slot: "20", title: "Pricing Sheet", description: "Plans, features, usage limits, discounts.", tier: "C", roles: ["sales", "marketing", "support"], sourceStages: ["VALIDATION", "FINANCE"], templatePath: "08-sales-marketing/20-pricing-sheet.md.hbs", placeholders: ["COMPANY_NAME", "TIERS", "CURRENT_DATE"] },
  { id: "proposal-template", category: "08-sales-marketing", slot: "21", title: "Proposal Template", description: "Formal offer to customers.", tier: "D", roles: ["sales", "founder"], sourceStages: [], templatePath: "08-sales-marketing/21-proposal-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "sales-email-templates", category: "08-sales-marketing", slot: "22", title: "Sales Email Templates", description: "Outreach, follow-up, reactivation.", tier: "D", roles: ["sales"], sourceStages: [], templatePath: "08-sales-marketing/22-sales-email-templates.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "contract-approval-process", category: "08-sales-marketing", slot: "23", title: "Contract Approval Process", description: "Who can approve customer contracts.", tier: "D", roles: ["sales", "founder", "finance"], sourceStages: [], templatePath: "08-sales-marketing/23-contract-approval-process.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "lead-qualification", category: "08-sales-marketing", slot: "24", title: "Lead Qualification Criteria", description: "What makes a lead worth pursuing.", tier: "D", roles: ["sales"], sourceStages: [], templatePath: "08-sales-marketing/24-lead-qualification.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "customer-handoff-to-support", category: "08-sales-marketing", slot: "25", title: "Customer Handoff to Support", description: "What sales must pass to onboarding / support.", tier: "D", roles: ["sales", "support"], sourceStages: [], templatePath: "08-sales-marketing/25-customer-handoff-to-support.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 09-customer-success --------
  { id: "customer-onboarding-guide", category: "09-customer-success", slot: "00", title: "Customer Onboarding Guide", description: "How new customers get started.", tier: "C", roles: ["support", "sales", "founder"], sourceStages: ["PRODUCT_SPEC", "LAUNCH"], templatePath: "09-customer-success/00-customer-onboarding-guide.md.hbs", placeholders: ["COMPANY_NAME", "PRODUCT_NAME", "STEPS", "CURRENT_DATE"] },
  { id: "support-playbook", category: "09-customer-success", slot: "01", title: "Support Playbook", description: "How support tickets are handled.", tier: "D", roles: ["support"], sourceStages: [], templatePath: "09-customer-success/01-support-playbook.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "faq", category: "09-customer-success", slot: "02", title: "FAQ", description: "Common questions and answers.", tier: "C", roles: ["support", "sales", "marketing"], sourceStages: ["PRODUCT_SPEC"], templatePath: "09-customer-success/02-faq.md.hbs", placeholders: ["COMPANY_NAME", "QUESTIONS", "CURRENT_DATE"] },
  { id: "help-centre-structure", category: "09-customer-success", slot: "03", title: "Help Centre Structure", description: "Categories and article list.", tier: "D", roles: ["support", "marketing"], sourceStages: [], templatePath: "09-customer-success/03-help-centre-structure.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "support-macros", category: "09-customer-success", slot: "04", title: "Support Macros", description: "Reusable replies for support staff.", tier: "D", roles: ["support"], sourceStages: [], templatePath: "09-customer-success/04-support-macros.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "escalation-policy", category: "09-customer-success", slot: "05", title: "Escalation Policy", description: "When support escalates to engineering / product.", tier: "D", roles: ["support", "dev", "founder"], sourceStages: [], templatePath: "09-customer-success/05-escalation-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "sla-policy", category: "09-customer-success", slot: "06", title: "SLA Policy", description: "Response times and support levels.", tier: "D", roles: ["support", "sales", "founder"], sourceStages: [], templatePath: "09-customer-success/06-sla-policy.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "bug-report-template", category: "09-customer-success", slot: "07", title: "Bug Report Template", description: "How customers / staff report bugs.", tier: "D", roles: ["support", "dev"], sourceStages: [], templatePath: "09-customer-success/07-bug-report-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "feature-request-process", category: "09-customer-success", slot: "08", title: "Feature Request Process", description: "How requests are logged and reviewed.", tier: "D", roles: ["support", "dev", "founder"], sourceStages: [], templatePath: "09-customer-success/08-feature-request-process.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "customer-health-score", category: "09-customer-success", slot: "09", title: "Customer Health Score Model", description: "Usage, satisfaction, risk signals.", tier: "D", roles: ["support", "sales", "founder"], sourceStages: [], templatePath: "09-customer-success/09-customer-health-score.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "churn-risk-playbook", category: "09-customer-success", slot: "10", title: "Churn Risk Playbook", description: "How to save at-risk customers.", tier: "D", roles: ["support", "sales"], sourceStages: [], templatePath: "09-customer-success/10-churn-risk-playbook.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "cancellation-flow", category: "09-customer-success", slot: "11", title: "Cancellation Flow Document", description: "Cancellation reasons, save offers, data deletion.", tier: "D", roles: ["support", "dev", "founder"], sourceStages: [], templatePath: "09-customer-success/11-cancellation-flow.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "customer-training", category: "09-customer-success", slot: "12", title: "Customer Training Material", description: "Videos, guides, webinars, walkthroughs.", tier: "D", roles: ["support", "marketing"], sourceStages: [], templatePath: "09-customer-success/12-customer-training.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "knowledge-base-articles", category: "09-customer-success", slot: "13", title: "Knowledge Base Articles", description: "Step-by-step product help.", tier: "D", roles: ["support", "marketing"], sourceStages: [], templatePath: "09-customer-success/13-knowledge-base-articles.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

  // -------- 10-templates --------
  { id: "meeting-notes-template", category: "10-templates", slot: "00", title: "Meeting Notes Template", description: "Date, attendees, decisions, actions, follow-ups.", tier: "D", roles: ["founder", "dev", "designer", "marketing", "sales", "support", "finance", "contractor"], sourceStages: [], templatePath: "10-templates/00-meeting-notes-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "decision-log-template", category: "10-templates", slot: "01", title: "Decision Log Template", description: "Date, context, decision, rationale, owner.", tier: "D", roles: ["founder", "dev", "designer"], sourceStages: [], templatePath: "10-templates/01-decision-log-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "prd-template", category: "10-templates", slot: "02", title: "PRD Template", description: "Blank PRD founders use for v2 features.", tier: "D", roles: ["founder", "dev", "designer"], sourceStages: [], templatePath: "10-templates/02-prd-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "bug-report-form", category: "10-templates", slot: "03", title: "Bug Report Form", description: "Blank form template: steps to reproduce, expected, actual, environment, severity.", tier: "D", roles: ["dev", "support"], sourceStages: [], templatePath: "10-templates/03-bug-report-form.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "feature-request-template", category: "10-templates", slot: "04", title: "Feature Request Template", description: "Problem, proposed solution, user, success criteria.", tier: "D", roles: ["dev", "founder", "support"], sourceStages: [], templatePath: "10-templates/04-feature-request-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "adr-template", category: "10-templates", slot: "05", title: "Architecture Decision Record", description: "Context, decision, consequences, status.", tier: "D", roles: ["dev"], sourceStages: [], templatePath: "10-templates/05-adr-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "1-on-1-template", category: "10-templates", slot: "06", title: "1-on-1 Meeting Template", description: "Manager / direct report agenda + action log.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "10-templates/06-1-on-1-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "weekly-update-template", category: "10-templates", slot: "07", title: "Weekly Update Template", description: "Highlights, lowlights, asks, metrics.", tier: "D", roles: ["founder", "dev", "support"], sourceStages: [], templatePath: "10-templates/07-weekly-update-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "rfc-template", category: "10-templates", slot: "08", title: "RFC Template", description: "Request-for-comments doc for cross-team changes.", tier: "D", roles: ["dev", "founder"], sourceStages: [], templatePath: "10-templates/08-rfc-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "incident-postmortem", category: "10-templates", slot: "09", title: "Incident Postmortem Template", description: "Timeline, impact, root cause, fix, prevention.", tier: "D", roles: ["dev", "support", "founder"], sourceStages: [], templatePath: "10-templates/09-incident-postmortem.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "interview-scorecard", category: "10-templates", slot: "10", title: "Interview Scorecard Template", description: "Per-candidate scoring against role scorecard.", tier: "D", roles: ["founder"], sourceStages: [], templatePath: "10-templates/10-interview-scorecard.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "user-research-script", category: "10-templates", slot: "11", title: "User Research Script Template", description: "Intro, warmup, tasks, debrief.", tier: "D", roles: ["designer", "founder"], sourceStages: [], templatePath: "10-templates/11-user-research-script.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "release-notes-template", category: "10-templates", slot: "12", title: "Release Notes Template", description: "Customer-facing release notes structure.", tier: "D", roles: ["dev", "marketing", "support"], sourceStages: [], templatePath: "10-templates/12-release-notes-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "sales-call-notes", category: "10-templates", slot: "13", title: "Sales Call Notes Template", description: "Lead, BANT, next step, follow-up date.", tier: "D", roles: ["sales"], sourceStages: [], templatePath: "10-templates/13-sales-call-notes.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },
  { id: "support-ticket-template", category: "10-templates", slot: "14", title: "Support Ticket Template", description: "Customer, severity, summary, resolution.", tier: "D", roles: ["support"], sourceStages: [], templatePath: "10-templates/14-support-ticket-template.md.hbs", placeholders: ["COMPANY_NAME", "COMPANY_SLUG", "CURRENT_DATE"] },

];

/** Total descriptor count across all categories. */
export const DOC_MANIFEST_COUNT = DOC_MANIFEST.length;

/** Look up a descriptor by id; undefined if missing. */
export function getDocById(id: string): DocDescriptor | undefined {
  return DOC_MANIFEST.find((d) => d.id === id);
}

/** All descriptors in a given category, in slot order. */
export function getDocsByCategory(
  category: DocDescriptor["category"]
): ReadonlyArray<DocDescriptor> {
  return DOC_MANIFEST.filter((d) => d.category === category).sort((a, b) =>
    a.slot.localeCompare(b.slot)
  );
}

/** All descriptors for a given role (role is in d.roles). */
export function getDocsForRole(
  role: DocDescriptor["roles"][number]
): ReadonlyArray<DocDescriptor> {
  return DOC_MANIFEST.filter((d) => d.roles.includes(role));
}

/** Per-tier counts -- the slice-2 test suite asserts these are stable. */
export function getTierCounts(): Record<DocDescriptor["tier"], number> {
  const counts: Record<DocDescriptor["tier"], number> = { A: 0, B: 0, C: 0, D: 0 };
  for (const d of DOC_MANIFEST) counts[d.tier]++;
  return counts;
}
