#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
/**
 * Tier-1 build-time optimization runner.
 *
 * Walks the static prompt definitions in @founder-os/prompts and the wireframe
 * orchestrator's prompt-engine, runs each through Prompt Master, and emits
 * .opt.ts sibling files containing the optimized values.
 *
 * Run: ANTHROPIC_API_KEY=sk-... node scripts/optimize-prompts.mjs
 *
 * Output:
 *   packages/prompts/src/system-prompts.opt.ts
 *   packages/prompts/src/templates.opt.ts
 *   ../wireframe-orchestrator-starter--wt-fc-claude-ggni0t/wireframe-orchestrator-starter/packages/prompt-engine/src/templates.opt.ts
 *
 * The originals are not modified. A barrel export can choose which set to
 * ship via env flag (see packages/prompts/src/index.ts).
 */
import { fileURLToPath } from "node:url";
import { createAnthropicFetchTransport, optimize, setTransport } from "@founder-os/prompt-master";
import { installNodeBackends } from "@founder-os/prompt-master/node";

// Node script — wire the disk-backed cache + telemetry so repeated
// optimize-prompts runs can reuse cached optimizations across invocations.
installNodeBackends();

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "..");

const apiKey = process.env.ANTHROPIC_API_KEY;
if (!apiKey) {
  console.error("ANTHROPIC_API_KEY not set. Optimization will fall back to no-op.");
  console.error("Set ANTHROPIC_API_KEY=sk-... and re-run to actually compress.");
}

if (apiKey) {
  setTransport(
    createAnthropicFetchTransport({
      apiKey,
      model: "claude-haiku-4-5-20251001",
    })
  );
}

const TARGETS = [
  resolve(ROOT, "packages/prompts/src/system-prompts.ts"),
  resolve(ROOT, "packages/prompts/src/templates.ts"),
  resolve(
    ROOT,
    "..",
    "wireframe-orchestrator-starter--wt-fc-claude-ggni0t",
    "wireframe-orchestrator-starter",
    "packages",
    "prompt-engine",
    "src",
    "templates.ts"
  ),
];

let totalSaved = 0;

for (const file of TARGETS) {
  let source;
  try {
    source = await readFile(file, "utf8");
  } catch (err) {
    console.warn(`[skip] ${file}: ${err.code ?? err.message}`);
    continue;
  }

  const exportRe = /export\s+const\s+(\w+)\s*=\s*(`[^`]+`|"(?:\\"|[^"])*")\s*;/g;
  const out = [
    "// AUTO-GENERATED by scripts/optimize-prompts.mjs. Do not edit by hand.",
    `// Source: ${file.split(/[\\/]/).slice(-3).join("/")}`,
    "",
  ];

  let count = 0;
  for (const m of source.matchAll(exportRe)) {
    const name = m[1];
    const literal = m[2];
    const original = literal.startsWith("`") ? literal.slice(1, -1) : JSON.parse(literal);
    const result = await optimize({
      prompt: original,
      context: "system",
    });
    totalSaved += result.tokensSaved;
    count++;
    const note = result.fallbackUsed
      ? " (fallback - original returned)"
      : ` (saved ~${result.tokensSaved} tokens)`;
    out.push(`// ${name}${note}`);
    out.push(`export const ${name}_OPTIMIZED = ${JSON.stringify(result.optimized)};`);
    out.push("");
  }

  if (count === 0) {
    console.log(`[skip] ${file}: no string-literal exports found`);
    continue;
  }

  const outPath = file.replace(/\.ts$/, ".opt.ts");
  await writeFile(outPath, out.join("\n"), "utf8");
  console.log(`[wrote] ${outPath}  (${count} exports)`);
}

console.log(`\nTotal estimated tokens saved across all static templates: ${totalSaved}`);
